package rekammedis;
import bridging.BPJSDataSEP;
import bridging.BPJSSuratKontrol;
import fungsi.koneksiDB;
import fungsi.sekuel;
import fungsi.validasi;
import fungsi.akses;
import java.awt.Cursor;
import java.awt.Desktop;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.text.Document;
import javax.swing.text.html.HTMLEditorKit;
import javax.swing.text.html.StyleSheet;
import kepegawaian.DlgCariDokter;
import kepegawaian.DlgCariPetugas;
import laporan.DlgDiagnosaPenyakit;

public class DlgERMRalan extends javax.swing.JDialog {
    private sekuel Sequel=new sekuel();
    private validasi Valid=new validasi();
    private Connection koneksi=koneksiDB.condb();
    private PreparedStatement ps,ps2;
    private ResultSet rs,rs2;
    private int i=0,x = 0;
    private DlgCariPetugas petugas=new DlgCariPetugas(null,false);
    private DlgCariDokter dokter=new DlgCariDokter(null,false);
    private String stts = "", kdkamar = "", gedung = "",kmr="",variabel="";
    
    /** Creates new form DlgProgramStudi
     * @param parent
     * @param modal */
    public DlgERMRalan(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        petugas.addWindowListener(new WindowListener() {
            @Override
            public void windowOpened(WindowEvent e) {}
            @Override
            public void windowClosing(WindowEvent e) {}
            @Override
            public void windowClosed(WindowEvent e) {
                if(petugas.getTable().getSelectedRow()!= -1){ 
                    if(i==1){
                        KdPetugas.setText(petugas.getTable().getValueAt(petugas.getTable().getSelectedRow(),0).toString());
                        NmPetugas.setText(petugas.getTable().getValueAt(petugas.getTable().getSelectedRow(),1).toString());  
                    }else{
                        KdPetugas2.setText(petugas.getTable().getValueAt(petugas.getTable().getSelectedRow(),0).toString());
                        NmPetugas2.setText(petugas.getTable().getValueAt(petugas.getTable().getSelectedRow(),1).toString());  
                    }
                         
                }              
            }
            @Override
            public void windowIconified(WindowEvent e) {}
            @Override
            public void windowDeiconified(WindowEvent e) {}
            @Override
            public void windowActivated(WindowEvent e) {}
            @Override
            public void windowDeactivated(WindowEvent e) {}
        });
        
        dokter.addWindowListener(new WindowListener() {
            @Override
            public void windowOpened(WindowEvent e) {}
            @Override
            public void windowClosing(WindowEvent e) {}
            @Override
            public void windowClosed(WindowEvent e) {
                if(dokter.getTable().getSelectedRow()!= -1){ 
                    KdDPJP.setText(dokter.getTable().getValueAt(dokter.getTable().getSelectedRow(),0).toString());
                    NmDPJP.setText(dokter.getTable().getValueAt(dokter.getTable().getSelectedRow(),1).toString());  
                }              
            }
            @Override
            public void windowIconified(WindowEvent e) {}
            @Override
            public void windowDeiconified(WindowEvent e) {}
            @Override
            public void windowActivated(WindowEvent e) {}
            @Override
            public void windowDeactivated(WindowEvent e) {}
        });
    }
    private Dimension screen=Toolkit.getDefaultToolkit().getScreenSize();

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        WindowDPJPranap = new javax.swing.JDialog();
        internalFrame15 = new widget.InternalFrame();
        KdDPJP = new widget.TextBox();
        NmDPJP = new widget.TextBox();
        btnDPJP = new widget.Button();
        KdPetugas = new widget.TextBox();
        NmPetugas = new widget.TextBox();
        KdPetugas2 = new widget.TextBox();
        NmPetugas2 = new widget.TextBox();
        internalFrame1 = new widget.InternalFrame();
        internalFrame4 = new widget.InternalFrame();
        jLabel3 = new widget.Label();
        TNoRW = new widget.TextBox();
        TNoRM = new widget.TextBox();
        TNmPasien = new widget.TextBox();
        jLabel13 = new widget.Label();
        jLabel4 = new widget.Label();
        TtglMasuk = new widget.TextBox();
        NoRawat = new widget.TextBox();
        NoSEP = new widget.TextBox();
        NoKartu = new widget.TextBox();
        NoRM = new widget.TextBox();
        NmPasien = new widget.TextBox();
        TabRekamMedis = new javax.swing.JTabbedPane();
        scrollInput = new widget.ScrollPane();
        FormInput = new widget.PanelBiasa();
        BtnAwalKeperawatan = new widget.ButtonBig();
        BtnAwalKebidanan = new widget.ButtonBig();
        BtnAwalKepAnak = new widget.ButtonBig();
        BtnAwalKepGeriatri = new widget.ButtonBig();
        BtnTransferRuang = new widget.ButtonBig();
        BtnResume = new widget.ButtonBig();
        BtnRisikoJatuh = new widget.ButtonBig();
        BtnRisikoJatuhAnak = new widget.ButtonBig();
        BtnRisikoJatuhGeriatri = new widget.ButtonBig();
        BtnRisikoJatuhLansia = new widget.ButtonBig();
        BtnSkriningTB = new widget.ButtonBig();
        BtnUSGKandungan = new widget.ButtonBig();
        BtnUSGGynekologi = new widget.ButtonBig();
        scrollInput1 = new widget.ScrollPane();
        FormInput1 = new widget.PanelBiasa();
        BtnDataSep = new widget.ButtonBig();
        BtnSurkon = new widget.ButtonBig();
        BtnDiagnosa = new widget.ButtonBig();
        panelisi1 = new widget.panelisi();
        label9 = new widget.Label();
        BtnRefres = new widget.Button();
        BtnKeluar = new widget.Button();

        WindowDPJPranap.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        WindowDPJPranap.setName("WindowDPJPranap"); // NOI18N
        WindowDPJPranap.setUndecorated(true);
        WindowDPJPranap.setResizable(false);

        internalFrame15.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255), 3), "::[ DPJP Rawat Inap ]::", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        internalFrame15.setName("internalFrame15"); // NOI18N
        internalFrame15.setWarnaBawah(new java.awt.Color(245, 250, 240));
        internalFrame15.setLayout(null);

        KdDPJP.setEditable(false);
        KdDPJP.setForeground(new java.awt.Color(0, 0, 0));
        KdDPJP.setName("KdDPJP"); // NOI18N
        internalFrame15.add(KdDPJP);
        KdDPJP.setBounds(81, 32, 100, 23);

        NmDPJP.setEditable(false);
        NmDPJP.setForeground(new java.awt.Color(0, 0, 0));
        NmDPJP.setName("NmDPJP"); // NOI18N
        internalFrame15.add(NmDPJP);
        NmDPJP.setBounds(183, 32, 380, 23);

        btnDPJP.setForeground(new java.awt.Color(0, 0, 0));
        btnDPJP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/190.png"))); // NOI18N
        btnDPJP.setMnemonic('7');
        btnDPJP.setToolTipText("ALt+7");
        btnDPJP.setName("btnDPJP"); // NOI18N
        btnDPJP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDPJPActionPerformed(evt);
            }
        });
        internalFrame15.add(btnDPJP);
        btnDPJP.setBounds(565, 32, 28, 23);

        KdPetugas.setEditable(false);
        KdPetugas.setForeground(new java.awt.Color(0, 0, 0));
        KdPetugas.setName("KdPetugas"); // NOI18N
        internalFrame15.add(KdPetugas);
        KdPetugas.setBounds(81, 32, 100, 23);

        NmPetugas.setEditable(false);
        NmPetugas.setForeground(new java.awt.Color(0, 0, 0));
        NmPetugas.setName("NmPetugas"); // NOI18N
        internalFrame15.add(NmPetugas);
        NmPetugas.setBounds(81, 32, 100, 23);

        KdPetugas2.setEditable(false);
        KdPetugas2.setForeground(new java.awt.Color(0, 0, 0));
        KdPetugas2.setName("KdPetugas2"); // NOI18N
        internalFrame15.add(KdPetugas2);
        KdPetugas2.setBounds(81, 32, 100, 23);

        NmPetugas2.setEditable(false);
        NmPetugas2.setForeground(new java.awt.Color(0, 0, 0));
        NmPetugas2.setName("NmPetugas2"); // NOI18N
        internalFrame15.add(NmPetugas2);
        NmPetugas2.setBounds(81, 32, 100, 23);

        WindowDPJPranap.getContentPane().add(internalFrame15, java.awt.BorderLayout.CENTER);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        internalFrame1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 245, 235)), "::[ ERM INAP ]::", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(50, 50, 50))); // NOI18N
        internalFrame1.setName("internalFrame1"); // NOI18N
        internalFrame1.setLayout(new java.awt.BorderLayout(1, 1));

        internalFrame4.setName("internalFrame4"); // NOI18N
        internalFrame4.setPreferredSize(new java.awt.Dimension(12, 100));
        internalFrame4.setLayout(null);

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("NoRawat/RM :");
        jLabel3.setName("jLabel3"); // NOI18N
        internalFrame4.add(jLabel3);
        jLabel3.setBounds(0, 10, 103, 23);

        TNoRW.setEditable(false);
        TNoRW.setForeground(new java.awt.Color(0, 0, 0));
        TNoRW.setName("TNoRW"); // NOI18N
        internalFrame4.add(TNoRW);
        TNoRW.setBounds(107, 10, 122, 23);

        TNoRM.setEditable(false);
        TNoRM.setForeground(new java.awt.Color(0, 0, 0));
        TNoRM.setName("TNoRM"); // NOI18N
        internalFrame4.add(TNoRM);
        TNoRM.setBounds(230, 10, 70, 23);

        TNmPasien.setEditable(false);
        TNmPasien.setForeground(new java.awt.Color(0, 0, 0));
        TNmPasien.setName("TNmPasien"); // NOI18N
        internalFrame4.add(TNmPasien);
        TNmPasien.setBounds(110, 40, 280, 23);

        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Nama :");
        jLabel13.setName("jLabel13"); // NOI18N
        internalFrame4.add(jLabel13);
        jLabel13.setBounds(0, 38, 103, 23);

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Tanggal Regis :");
        jLabel4.setName("jLabel4"); // NOI18N
        internalFrame4.add(jLabel4);
        jLabel4.setBounds(0, 66, 103, 23);

        TtglMasuk.setEditable(false);
        TtglMasuk.setForeground(new java.awt.Color(0, 0, 0));
        TtglMasuk.setName("TtglMasuk"); // NOI18N
        internalFrame4.add(TtglMasuk);
        TtglMasuk.setBounds(107, 66, 280, 23);

        NoRawat.setEditable(false);
        NoRawat.setForeground(new java.awt.Color(0, 0, 0));
        NoRawat.setName("NoRawat"); // NOI18N
        internalFrame4.add(NoRawat);
        NoRawat.setBounds(107, 10, 122, 23);

        NoSEP.setEditable(false);
        NoSEP.setForeground(new java.awt.Color(0, 0, 0));
        NoSEP.setName("NoSEP"); // NOI18N
        internalFrame4.add(NoSEP);
        NoSEP.setBounds(107, 10, 122, 23);

        NoKartu.setEditable(false);
        NoKartu.setForeground(new java.awt.Color(0, 0, 0));
        NoKartu.setName("NoKartu"); // NOI18N
        internalFrame4.add(NoKartu);
        NoKartu.setBounds(107, 10, 122, 23);

        NoRM.setEditable(false);
        NoRM.setForeground(new java.awt.Color(0, 0, 0));
        NoRM.setName("NoRM"); // NOI18N
        internalFrame4.add(NoRM);
        NoRM.setBounds(107, 10, 122, 23);

        NmPasien.setEditable(false);
        NmPasien.setForeground(new java.awt.Color(0, 0, 0));
        NmPasien.setName("NmPasien"); // NOI18N
        internalFrame4.add(NmPasien);
        NmPasien.setBounds(107, 10, 122, 23);

        internalFrame1.add(internalFrame4, java.awt.BorderLayout.PAGE_START);

        TabRekamMedis.setBackground(new java.awt.Color(255, 255, 254));
        TabRekamMedis.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        TabRekamMedis.setName("TabRekamMedis"); // NOI18N
        TabRekamMedis.setPreferredSize(new java.awt.Dimension(270, 106));

        scrollInput.setName("scrollInput"); // NOI18N
        scrollInput.setPreferredSize(new java.awt.Dimension(102, 557));

        FormInput.setBackground(new java.awt.Color(255, 255, 255));
        FormInput.setBorder(null);
        FormInput.setName("FormInput"); // NOI18N
        FormInput.setPreferredSize(new java.awt.Dimension(870, 834));
        FormInput.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 8, 25));

        BtnAwalKeperawatan.setForeground(new java.awt.Color(0, 0, 0));
        BtnAwalKeperawatan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/2620509_employee_job_note_seeker_unemployee_icon.png"))); // NOI18N
        BtnAwalKeperawatan.setText("Asesmen Awal Keperawatan");
        BtnAwalKeperawatan.setIconTextGap(0);
        BtnAwalKeperawatan.setName("BtnAwalKeperawatan"); // NOI18N
        BtnAwalKeperawatan.setPreferredSize(new java.awt.Dimension(200, 90));
        BtnAwalKeperawatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAwalKeperawatanActionPerformed(evt);
            }
        });
        FormInput.add(BtnAwalKeperawatan);

        BtnAwalKebidanan.setForeground(new java.awt.Color(0, 0, 0));
        BtnAwalKebidanan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/2620509_employee_job_note_seeker_unemployee_icon.png"))); // NOI18N
        BtnAwalKebidanan.setText("Asesmen Awal Kebidanan");
        BtnAwalKebidanan.setIconTextGap(0);
        BtnAwalKebidanan.setName("BtnAwalKebidanan"); // NOI18N
        BtnAwalKebidanan.setPreferredSize(new java.awt.Dimension(200, 90));
        BtnAwalKebidanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAwalKebidananActionPerformed(evt);
            }
        });
        FormInput.add(BtnAwalKebidanan);

        BtnAwalKepAnak.setForeground(new java.awt.Color(0, 0, 0));
        BtnAwalKepAnak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/2620509_employee_job_note_seeker_unemployee_icon.png"))); // NOI18N
        BtnAwalKepAnak.setText("Awal Keprawatan Anak");
        BtnAwalKepAnak.setIconTextGap(0);
        BtnAwalKepAnak.setName("BtnAwalKepAnak"); // NOI18N
        BtnAwalKepAnak.setPreferredSize(new java.awt.Dimension(200, 90));
        BtnAwalKepAnak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAwalKepAnakActionPerformed(evt);
            }
        });
        FormInput.add(BtnAwalKepAnak);

        BtnAwalKepGeriatri.setForeground(new java.awt.Color(0, 0, 0));
        BtnAwalKepGeriatri.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/2620509_employee_job_note_seeker_unemployee_icon.png"))); // NOI18N
        BtnAwalKepGeriatri.setText("Awal Keprawatan Geriatri");
        BtnAwalKepGeriatri.setIconTextGap(0);
        BtnAwalKepGeriatri.setName("BtnAwalKepGeriatri"); // NOI18N
        BtnAwalKepGeriatri.setPreferredSize(new java.awt.Dimension(200, 90));
        BtnAwalKepGeriatri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAwalKepGeriatriActionPerformed(evt);
            }
        });
        FormInput.add(BtnAwalKepGeriatri);

        BtnTransferRuang.setForeground(new java.awt.Color(0, 0, 0));
        BtnTransferRuang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/1481002123_wheelchair.png"))); // NOI18N
        BtnTransferRuang.setText("Lembar Transfer Ruang");
        BtnTransferRuang.setIconTextGap(0);
        BtnTransferRuang.setName("BtnTransferRuang"); // NOI18N
        BtnTransferRuang.setPreferredSize(new java.awt.Dimension(200, 90));
        BtnTransferRuang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTransferRuangActionPerformed(evt);
            }
        });
        FormInput.add(BtnTransferRuang);

        BtnResume.setForeground(new java.awt.Color(0, 0, 0));
        BtnResume.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/2620524_cv_employee_job_seeker_unemployee_icon.png"))); // NOI18N
        BtnResume.setText("Resume Medis");
        BtnResume.setIconTextGap(0);
        BtnResume.setName("BtnResume"); // NOI18N
        BtnResume.setPreferredSize(new java.awt.Dimension(200, 90));
        BtnResume.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnResumeActionPerformed(evt);
            }
        });
        FormInput.add(BtnResume);

        BtnRisikoJatuh.setForeground(new java.awt.Color(0, 0, 0));
        BtnRisikoJatuh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/iconfinder_dialog-warning_118940.png"))); // NOI18N
        BtnRisikoJatuh.setText("Risiko Jatuh Dewasa");
        BtnRisikoJatuh.setIconTextGap(0);
        BtnRisikoJatuh.setName("BtnRisikoJatuh"); // NOI18N
        BtnRisikoJatuh.setPreferredSize(new java.awt.Dimension(200, 90));
        BtnRisikoJatuh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRisikoJatuhActionPerformed(evt);
            }
        });
        FormInput.add(BtnRisikoJatuh);

        BtnRisikoJatuhAnak.setForeground(new java.awt.Color(0, 0, 0));
        BtnRisikoJatuhAnak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/iconfinder_dialog-warning_118940.png"))); // NOI18N
        BtnRisikoJatuhAnak.setText("Risiko Jatuh Anak");
        BtnRisikoJatuhAnak.setIconTextGap(0);
        BtnRisikoJatuhAnak.setName("BtnRisikoJatuhAnak"); // NOI18N
        BtnRisikoJatuhAnak.setPreferredSize(new java.awt.Dimension(200, 90));
        BtnRisikoJatuhAnak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRisikoJatuhAnakActionPerformed(evt);
            }
        });
        FormInput.add(BtnRisikoJatuhAnak);

        BtnRisikoJatuhGeriatri.setForeground(new java.awt.Color(0, 0, 0));
        BtnRisikoJatuhGeriatri.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/iconfinder_dialog-warning_118940.png"))); // NOI18N
        BtnRisikoJatuhGeriatri.setText("Risiko Jatuh Geriatri");
        BtnRisikoJatuhGeriatri.setIconTextGap(0);
        BtnRisikoJatuhGeriatri.setName("BtnRisikoJatuhGeriatri"); // NOI18N
        BtnRisikoJatuhGeriatri.setPreferredSize(new java.awt.Dimension(200, 90));
        BtnRisikoJatuhGeriatri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRisikoJatuhGeriatriActionPerformed(evt);
            }
        });
        FormInput.add(BtnRisikoJatuhGeriatri);

        BtnRisikoJatuhLansia.setForeground(new java.awt.Color(0, 0, 0));
        BtnRisikoJatuhLansia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/iconfinder_dialog-warning_118940.png"))); // NOI18N
        BtnRisikoJatuhLansia.setText("Risiko Jatuh Lansia");
        BtnRisikoJatuhLansia.setIconTextGap(0);
        BtnRisikoJatuhLansia.setName("BtnRisikoJatuhLansia"); // NOI18N
        BtnRisikoJatuhLansia.setPreferredSize(new java.awt.Dimension(200, 90));
        BtnRisikoJatuhLansia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRisikoJatuhLansiaActionPerformed(evt);
            }
        });
        FormInput.add(BtnRisikoJatuhLansia);

        BtnSkriningTB.setForeground(new java.awt.Color(0, 0, 0));
        BtnSkriningTB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/6009767_avatar_healthcare_male_mask_medical_icon.png"))); // NOI18N
        BtnSkriningTB.setText("Skrining TB");
        BtnSkriningTB.setIconTextGap(0);
        BtnSkriningTB.setName("BtnSkriningTB"); // NOI18N
        BtnSkriningTB.setPreferredSize(new java.awt.Dimension(200, 90));
        BtnSkriningTB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSkriningTBActionPerformed(evt);
            }
        });
        FormInput.add(BtnSkriningTB);

        BtnUSGKandungan.setForeground(new java.awt.Color(0, 0, 0));
        BtnUSGKandungan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/375263_scan_scans_ultra sound_ultrasound_icon.png"))); // NOI18N
        BtnUSGKandungan.setText("USG Kandungan");
        BtnUSGKandungan.setIconTextGap(0);
        BtnUSGKandungan.setName("BtnUSGKandungan"); // NOI18N
        BtnUSGKandungan.setPreferredSize(new java.awt.Dimension(200, 90));
        BtnUSGKandungan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnUSGKandunganActionPerformed(evt);
            }
        });
        FormInput.add(BtnUSGKandungan);

        BtnUSGGynekologi.setForeground(new java.awt.Color(0, 0, 0));
        BtnUSGGynekologi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/375257_uterus_icon.png"))); // NOI18N
        BtnUSGGynekologi.setText("USG Gynekologi");
        BtnUSGGynekologi.setIconTextGap(0);
        BtnUSGGynekologi.setName("BtnUSGGynekologi"); // NOI18N
        BtnUSGGynekologi.setPreferredSize(new java.awt.Dimension(200, 90));
        BtnUSGGynekologi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnUSGGynekologiActionPerformed(evt);
            }
        });
        FormInput.add(BtnUSGGynekologi);

        scrollInput.setViewportView(FormInput);

        TabRekamMedis.addTab("RM Rawat Jalan", scrollInput);

        scrollInput1.setName("scrollInput1"); // NOI18N
        scrollInput1.setPreferredSize(new java.awt.Dimension(102, 557));

        FormInput1.setBackground(new java.awt.Color(255, 255, 255));
        FormInput1.setBorder(null);
        FormInput1.setName("FormInput1"); // NOI18N
        FormInput1.setPreferredSize(new java.awt.Dimension(870, 834));
        FormInput1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 8, 25));

        BtnDataSep.setForeground(new java.awt.Color(0, 0, 0));
        BtnDataSep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/bpjs.png"))); // NOI18N
        BtnDataSep.setText("DATA SEP");
        BtnDataSep.setIconTextGap(0);
        BtnDataSep.setName("BtnDataSep"); // NOI18N
        BtnDataSep.setPreferredSize(new java.awt.Dimension(200, 90));
        BtnDataSep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDataSepActionPerformed(evt);
            }
        });
        FormInput1.add(BtnDataSep);

        BtnSurkon.setForeground(new java.awt.Color(0, 0, 0));
        BtnSurkon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/bpjs.png"))); // NOI18N
        BtnSurkon.setText("Surat Kontrol");
        BtnSurkon.setIconTextGap(0);
        BtnSurkon.setName("BtnSurkon"); // NOI18N
        BtnSurkon.setPreferredSize(new java.awt.Dimension(200, 90));
        BtnSurkon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSurkonActionPerformed(evt);
            }
        });
        FormInput1.add(BtnSurkon);

        BtnDiagnosa.setForeground(new java.awt.Color(0, 0, 0));
        BtnDiagnosa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/health.png"))); // NOI18N
        BtnDiagnosa.setText("Diagnosa");
        BtnDiagnosa.setIconTextGap(0);
        BtnDiagnosa.setName("BtnDiagnosa"); // NOI18N
        BtnDiagnosa.setPreferredSize(new java.awt.Dimension(200, 90));
        BtnDiagnosa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDiagnosaActionPerformed(evt);
            }
        });
        FormInput1.add(BtnDiagnosa);

        scrollInput1.setViewportView(FormInput1);

        TabRekamMedis.addTab("File BPJS", scrollInput1);

        internalFrame1.add(TabRekamMedis, java.awt.BorderLayout.CENTER);

        panelisi1.setName("panelisi1"); // NOI18N
        panelisi1.setPreferredSize(new java.awt.Dimension(100, 56));
        panelisi1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 9));

        label9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label9.setName("label9"); // NOI18N
        label9.setPreferredSize(new java.awt.Dimension(20, 30));
        panelisi1.add(label9);

        BtnRefres.setForeground(new java.awt.Color(0, 0, 0));
        BtnRefres.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/42a.png"))); // NOI18N
        BtnRefres.setMnemonic('R');
        BtnRefres.setText("Refresh Rekam Medis");
        BtnRefres.setToolTipText("Alt+R");
        BtnRefres.setName("BtnRefres"); // NOI18N
        BtnRefres.setPreferredSize(new java.awt.Dimension(186, 30));
        BtnRefres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRefresActionPerformed(evt);
            }
        });
        panelisi1.add(BtnRefres);

        BtnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/exit.png"))); // NOI18N
        BtnKeluar.setMnemonic('K');
        BtnKeluar.setText("Keluar");
        BtnKeluar.setToolTipText("Alt+K");
        BtnKeluar.setName("BtnKeluar"); // NOI18N
        BtnKeluar.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKeluarActionPerformed(evt);
            }
        });
        BtnKeluar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnKeluarKeyPressed(evt);
            }
        });
        panelisi1.add(BtnKeluar);

        internalFrame1.add(panelisi1, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(internalFrame1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
/*
private void KdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TKdKeyPressed
    Valid.pindah(evt,BtnCari,Nm);
}//GEN-LAST:event_TKdKeyPressed
*/

    private void BtnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKeluarActionPerformed
        dispose();
    }//GEN-LAST:event_BtnKeluarActionPerformed

    private void BtnKeluarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnKeluarKeyPressed
        TNoRW.setText("");
        TNoRM.setText("");
        TNmPasien.setText("");
        stts = "";
        kdkamar = "";        
        gedung = "";
        TtglMasuk.setText("");
        dispose();
    }//GEN-LAST:event_BtnKeluarKeyPressed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        isCek();
    }//GEN-LAST:event_formWindowOpened

    private void BtnRefresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRefresActionPerformed
        tombolCek(TNoRW.getText());
    }//GEN-LAST:event_BtnRefresActionPerformed

    private void BtnDataSepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDataSepActionPerformed
        if(TNoRW.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null,"Maaf, Silahkan anda pilih dulu dengan menklik data pada table...!!!");
            }else{
                this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
                BPJSDataSEP dlgki=new BPJSDataSEP(null,false);
                dlgki.setSize(internalFrame1.getWidth()-20,internalFrame1.getHeight()-20);
                dlgki.setLocationRelativeTo(internalFrame1);
                dlgki.isCek();
                dlgki.setNoRm2(TNoRW.getText());   
                dlgki.setVisible(true);
                this.setCursor(Cursor.getDefaultCursor());
        }
    }//GEN-LAST:event_BtnDataSepActionPerformed

    private void btnDPJPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDPJPActionPerformed
        akses.setform("DlgERMRalan");
        dokter.emptTeks();
        dokter.isCek();
        dokter.setSize(internalFrame1.getWidth(), internalFrame1.getHeight());
        dokter.setLocationRelativeTo(internalFrame1);
        dokter.setVisible(true);
    }//GEN-LAST:event_btnDPJPActionPerformed

    private void BtnAwalKeperawatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAwalKeperawatanActionPerformed
        if (TNoRW.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, Silahkan anda pilih dulu salah satu datanya pada tabel...!!!");
        } else {
            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            akses.setform("DlgERMRalan");
            RMPenilaianAwalKeperawatanRalan form = new RMPenilaianAwalKeperawatanRalan(null, false);
            form.emptTeks();
            form.isCek();
            form.setNoRm2(TNoRW.getText());
            form.setSize(internalFrame1.getWidth(), internalFrame1.getHeight());
            form.setLocationRelativeTo(internalFrame1);
            form.setVisible(true);
            this.setCursor(Cursor.getDefaultCursor());
        }// TODO add your handling code here:
    }//GEN-LAST:event_BtnAwalKeperawatanActionPerformed

    private void BtnAwalKebidananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAwalKebidananActionPerformed
        if (TNoRW.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, Silahkan anda pilih dulu salah satu datanya pada tabel...!!!");
        } else {
            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            akses.setform("DlgERMRalan");
            RMPenilaianAwalKeperawatanKebidanan form = new RMPenilaianAwalKeperawatanKebidanan (null, false);
            form.emptTeks();
            form.isCek();
            form.setNoRm2(TNoRW.getText());
            form.setSize(internalFrame1.getWidth(), internalFrame1.getHeight());
            form.setLocationRelativeTo(internalFrame1);
            form.setVisible(true);
            this.setCursor(Cursor.getDefaultCursor());
        }// TODO add your handling code here:
    }//GEN-LAST:event_BtnAwalKebidananActionPerformed

    private void BtnTransferRuangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTransferRuangActionPerformed
        if (TNoRW.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, Silahkan anda pilih dulu salah satu datanya pada tabel...!!!");
        } else {
            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            akses.setform("DlgERMRalan");
            RMTransferPasienAntarRuang form = new RMTransferPasienAntarRuang(null, false);
            form.emptTeks();
            form.isCek();
            form.setNoRm2(TNoRW.getText());
            form.setSize(internalFrame1.getWidth(), internalFrame1.getHeight());
            form.setLocationRelativeTo(internalFrame1);
            form.setVisible(true);
            this.setCursor(Cursor.getDefaultCursor());
        }// TODO add your handling code here:
    }//GEN-LAST:event_BtnTransferRuangActionPerformed

    private void BtnAwalKepAnakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAwalKepAnakActionPerformed
        if (TNoRW.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, Silahkan anda pilih dulu salah satu datanya pada tabel...!!!");
        } else {
            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            akses.setform("DlgERMRalan");
            RMPenilaianAwalKeperawatanBayiAnak form = new RMPenilaianAwalKeperawatanBayiAnak (null, false);
            form.emptTeks();
            form.isCek();
            form.setNoRm2(TNoRW.getText());
            form.setSize(internalFrame1.getWidth(), internalFrame1.getHeight());
            form.setLocationRelativeTo(internalFrame1);
            form.setVisible(true);
            this.setCursor(Cursor.getDefaultCursor());
        }// TODO add your handling code here:
    }//GEN-LAST:event_BtnAwalKepAnakActionPerformed

    private void BtnAwalKepGeriatriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAwalKepGeriatriActionPerformed
        if (TNoRW.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, Silahkan anda pilih dulu salah satu datanya pada tabel...!!!");
        } else {
            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            akses.setform("DlgERMRalan");
            RMPenilaianAwalKeperawatanRalanGeriatri form = new RMPenilaianAwalKeperawatanRalanGeriatri (null, false);
            form.emptTeks();
            form.isCek();
            form.setNoRm2(TNoRW.getText());
            form.setSize(internalFrame1.getWidth(), internalFrame1.getHeight());
            form.setLocationRelativeTo(internalFrame1);
            form.setVisible(true);
            this.setCursor(Cursor.getDefaultCursor());
        }// TODO add your handling code here:
    }//GEN-LAST:event_BtnAwalKepGeriatriActionPerformed

    private void BtnDiagnosaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDiagnosaActionPerformed
        if (TNoRW.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, Silahkan anda pilih dulu salah satu datanya pada tabel...!!!");
        } else {
                this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            akses.setform("DlgERMRalan");
            DlgDiagnosaPenyakit form = new DlgDiagnosaPenyakit(null, false);
            form.isCek();
            form.setPasien(TNoRW.getText());
            form.setSize(internalFrame1.getWidth(), internalFrame1.getHeight());
            form.setLocationRelativeTo(internalFrame1);
            form.setVisible(true);
            this.setCursor(Cursor.getDefaultCursor());
        }// TODO add your handling code here:
    }//GEN-LAST:event_BtnDiagnosaActionPerformed

    private void BtnResumeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnResumeActionPerformed
        if (TNoRW.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, Silahkan anda pilih dulu salah satu datanya pada tabel...!!!");
        } else {
            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            akses.setform("DlgERMRalan");
            RMDataResumePasien form = new RMDataResumePasien (null, false);
            form.emptTeks();
            form.isCek();
            form.setPasien(TNoRW.getText());
            form.setSize(internalFrame1.getWidth(), internalFrame1.getHeight());
            form.setLocationRelativeTo(internalFrame1);
            form.setVisible(true);
            this.setCursor(Cursor.getDefaultCursor());
        }// TODO add your handling code here:
    }//GEN-LAST:event_BtnResumeActionPerformed

    private void BtnRisikoJatuhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRisikoJatuhActionPerformed
        if (TNoRW.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, Silahkan anda pilih dulu salah satu datanya pada tabel...!!!");
        } else {
            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            akses.setform("DlgERMRalan");
            RMPenilaianLanjutanRisikoJatuhDewasa form = new RMPenilaianLanjutanRisikoJatuhDewasa (null, false);
            form.emptTeks();
            form.isCek();
            form.setNoRm2(TNoRW.getText());
            form.setSize(internalFrame1.getWidth(), internalFrame1.getHeight());
            form.setLocationRelativeTo(internalFrame1);
            form.setVisible(true);
            this.setCursor(Cursor.getDefaultCursor());
        }// TODO add your handling code here:
    }//GEN-LAST:event_BtnRisikoJatuhActionPerformed

    private void BtnRisikoJatuhAnakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRisikoJatuhAnakActionPerformed
        if (TNoRW.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, Silahkan anda pilih dulu salah satu datanya pada tabel...!!!");
        } else {
            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            akses.setform("DlgERMRalan");
            RMPenilaianLanjutanRisikoJatuhAnak form = new RMPenilaianLanjutanRisikoJatuhAnak (null, false);
            form.emptTeks();
            form.isCek();
            form.setNoRm2(TNoRW.getText());
            form.setSize(internalFrame1.getWidth(), internalFrame1.getHeight());
            form.setLocationRelativeTo(internalFrame1);
            form.setVisible(true);
            this.setCursor(Cursor.getDefaultCursor());
        }// TODO add your handling code here:
    }//GEN-LAST:event_BtnRisikoJatuhAnakActionPerformed

    private void BtnRisikoJatuhGeriatriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRisikoJatuhGeriatriActionPerformed
        if (TNoRW.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, Silahkan anda pilih dulu salah satu datanya pada tabel...!!!");
        } else {
            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            akses.setform("DlgERMRalan");
            RMPenilaianLanjutanRisikoJatuhGeriatri form = new RMPenilaianLanjutanRisikoJatuhGeriatri (null, false);
            form.emptTeks();
            form.isCek();
            form.setNoRm2(TNoRW.getText());
            form.setSize(internalFrame1.getWidth(), internalFrame1.getHeight());
            form.setLocationRelativeTo(internalFrame1);
            form.setVisible(true);
            this.setCursor(Cursor.getDefaultCursor());
        }// TODO add your handling code here:
    }//GEN-LAST:event_BtnRisikoJatuhGeriatriActionPerformed

    private void BtnRisikoJatuhLansiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRisikoJatuhLansiaActionPerformed
        if (TNoRW.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, Silahkan anda pilih dulu salah satu datanya pada tabel...!!!");
        } else {
            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            akses.setform("DlgERMRalan");
            RMPenilaianLanjutanRisikoJatuhLansia form = new RMPenilaianLanjutanRisikoJatuhLansia (null, false);
            form.emptTeks();
            form.isCek();
            form.setNoRm2(TNoRW.getText());
            form.setSize(internalFrame1.getWidth(), internalFrame1.getHeight());
            form.setLocationRelativeTo(internalFrame1);
            form.setVisible(true);
            this.setCursor(Cursor.getDefaultCursor());
        }// TODO add your handling code here:
    }//GEN-LAST:event_BtnRisikoJatuhLansiaActionPerformed

    private void BtnSurkonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSurkonActionPerformed
        if(TNoRW.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null,"Maaf, Silahkan anda pilih dulu dengan menklik data pada table...!!!");
            }else{
                this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
                BPJSSuratKontrol dlgki=new BPJSSuratKontrol(null,false);
                dlgki.setSize(internalFrame1.getWidth()-20,internalFrame1.getHeight()-20);
                dlgki.setLocationRelativeTo(internalFrame1);
                dlgki.isCek();
                dlgki.setNoRm(NoRawat.getText());
                dlgki.setVisible(true);
                this.setCursor(Cursor.getDefaultCursor());
        }// TODO add your handling code here:
    }//GEN-LAST:event_BtnSurkonActionPerformed

    private void BtnSkriningTBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSkriningTBActionPerformed
        if (TNoRW.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, Silahkan anda pilih dulu salah satu datanya pada tabel...!!!");
        } else {
            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            akses.setform("DlgERMRalan");
            RMSkriningTBC form = new RMSkriningTBC (null, false);
            form.emptTeks();
            form.isCek();
            form.setNoRm2(TNoRW.getText());
            form.setSize(internalFrame1.getWidth(), internalFrame1.getHeight());
            form.setLocationRelativeTo(internalFrame1);
            form.setVisible(true);
            this.setCursor(Cursor.getDefaultCursor());
        }// TODO add your handling code here:
    }//GEN-LAST:event_BtnSkriningTBActionPerformed

    private void BtnUSGKandunganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnUSGKandunganActionPerformed
        if (TNoRW.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, Silahkan anda pilih dulu salah satu datanya pada tabel...!!!");
        } else {
            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            RMHasilPemeriksaanUSG form= new RMHasilPemeriksaanUSG(null,false);
            form.emptTeks();
            form.isCek();
            form.setSize(internalFrame1.getWidth()-20,internalFrame1.getHeight()-20);
            form.setLocationRelativeTo(internalFrame1);
            form.setVisible(true);
            form.setNoRm2(TNoRW.getText());
            this.setCursor(Cursor.getDefaultCursor());
        }
    }//GEN-LAST:event_BtnUSGKandunganActionPerformed

    private void BtnUSGGynekologiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnUSGGynekologiActionPerformed
        if (TNoRW.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, Silahkan anda pilih dulu salah satu datanya pada tabel...!!!");
        } else {
            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            RMHasilUSGGynecolog form= new RMHasilUSGGynecolog(null,false);
            form.emptTeks();
            form.isCek();
            form.setSize(internalFrame1.getWidth()-20,internalFrame1.getHeight()-20);
            form.setLocationRelativeTo(internalFrame1);
            form.setVisible(true);
            form.setNoRm2(TNoRW.getText());
            this.setCursor(Cursor.getDefaultCursor());
        }
    }//GEN-LAST:event_BtnUSGGynekologiActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            DlgERMRalan dialog = new DlgERMRalan(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private widget.ButtonBig BtnAwalKebidanan;
    private widget.ButtonBig BtnAwalKepAnak;
    private widget.ButtonBig BtnAwalKepGeriatri;
    private widget.ButtonBig BtnAwalKeperawatan;
    private widget.ButtonBig BtnDataSep;
    private widget.ButtonBig BtnDiagnosa;
    private widget.Button BtnKeluar;
    private widget.Button BtnRefres;
    private widget.ButtonBig BtnResume;
    private widget.ButtonBig BtnRisikoJatuh;
    private widget.ButtonBig BtnRisikoJatuhAnak;
    private widget.ButtonBig BtnRisikoJatuhGeriatri;
    private widget.ButtonBig BtnRisikoJatuhLansia;
    private widget.ButtonBig BtnSkriningTB;
    private widget.ButtonBig BtnSurkon;
    private widget.ButtonBig BtnTransferRuang;
    private widget.ButtonBig BtnUSGGynekologi;
    private widget.ButtonBig BtnUSGKandungan;
    private widget.PanelBiasa FormInput;
    private widget.PanelBiasa FormInput1;
    private widget.TextBox KdDPJP;
    private widget.TextBox KdPetugas;
    private widget.TextBox KdPetugas2;
    private widget.TextBox NmDPJP;
    private widget.TextBox NmPasien;
    private widget.TextBox NmPetugas;
    private widget.TextBox NmPetugas2;
    private widget.TextBox NoKartu;
    private widget.TextBox NoRM;
    private widget.TextBox NoRawat;
    private widget.TextBox NoSEP;
    private widget.TextBox TNmPasien;
    private widget.TextBox TNoRM;
    private widget.TextBox TNoRW;
    private javax.swing.JTabbedPane TabRekamMedis;
    private widget.TextBox TtglMasuk;
    private javax.swing.JDialog WindowDPJPranap;
    private widget.Button btnDPJP;
    private widget.InternalFrame internalFrame1;
    private widget.InternalFrame internalFrame15;
    private widget.InternalFrame internalFrame4;
    private widget.Label jLabel13;
    private widget.Label jLabel3;
    private widget.Label jLabel4;
    private widget.Label label9;
    private widget.panelisi panelisi1;
    private widget.ScrollPane scrollInput;
    private widget.ScrollPane scrollInput1;
    // End of variables declaration//GEN-END:variables

    
    private void isCek() {
        BtnAwalKeperawatan.setEnabled(akses.getpenilaian_awal_keperawatan_ranap());
        BtnAwalKebidanan.setEnabled(akses.getpenilaian_awal_keperawatan_ranapkebidanan());
        BtnAwalKepAnak.setEnabled(akses.getpenilaian_awal_keperawatan_ranap_bayi());
        BtnAwalKepGeriatri.setEnabled(akses.getpenilaian_awal_keperawatan_ranap_neonatus());
        BtnTransferRuang.setEnabled(akses.gettransfer_pasien_antar_ruang());
        BtnResume.setEnabled(akses.getdata_resume_pasien());
        BtnRisikoJatuh.setEnabled(akses.getpenilaian_lanjutan_resiko_jatuh_dewasa());
        BtnRisikoJatuhAnak.setEnabled(akses.getpenilaian_lanjutan_resiko_jatuh_anak());
        BtnRisikoJatuhGeriatri.setEnabled(akses.getpenilaian_lanjutan_resiko_jatuh_geriatri());
        BtnRisikoJatuhLansia.setEnabled(akses.getpenilaian_lanjutan_resiko_jatuh_lansia());
        BtnSkriningTB.setEnabled(akses.getskrining_tbc());
        BtnDataSep.setEnabled(akses.getbpjs_sep());
        BtnSurkon.setEnabled(akses.getbpjs_surat_kontrol());
        BtnDiagnosa.setEnabled(akses.getdiagnosa_pasien());
    }
    
    public void setData(String norw, String norm, String nmpasien, 
            String ralan, String noreg, String TglINDONESIA) {
       TNoRW.setText(norw);
       TNoRM.setText(norm);
       TNmPasien.setText(nmpasien);
       TtglMasuk.setText(TglINDONESIA);
       tombolCek(norw);
    }
    
    private void tombolCek(String norawat) {
        if (Sequel.cariInteger("select count(-1) from penilaian_awal_keperawatan_ralan where no_rawat='" + norawat + "'") == 0) {
            BtnAwalKeperawatan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/2620509_employee_job_note_seeker_unemployee_icon.png")));
            BtnAwalKeperawatan.setToolTipText("Asesmen Awal Keperawatan Pasien Rawat Jalan BELUM diisi..!!!");
        } else {
            BtnAwalKeperawatan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/verif.png")));
            BtnAwalKeperawatan.setToolTipText("Asesmen Awal Keperawatan Pasien Rawat Jalan SUDAH diisi..!!!");
        }
        if (Sequel.cariInteger("select count(-1) from penilaian_awal_keperawatan_kebidanan_ranap where no_rawat='" + norawat + "'") == 0) {
            BtnAwalKebidanan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/2620509_employee_job_note_seeker_unemployee_icon.png")));
            BtnAwalKebidanan.setToolTipText("Asesmen Awal Kebidanan Pasien Rawat Jalan BELUM diisi..!!!");
        } else {
            BtnAwalKebidanan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/verif.png")));
            BtnAwalKebidanan.setToolTipText("Asesmen Awal Kebidanan Pasien Rawat Jalan SUDAH diisi..!!!");
        }
        if (Sequel.cariInteger("select count(-1) from penilaian_awal_keperawatan_ranap_bayi where no_rawat='" + norawat + "'") == 0) {
            BtnAwalKepAnak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/2620509_employee_job_note_seeker_unemployee_icon.png")));
            BtnAwalKepAnak.setToolTipText("Asesmen Awal Keperawatan Pasien Anak Rawat Jalan BELUM diisi..!!!");
        } else {
            BtnAwalKepAnak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/verif.png")));
            BtnAwalKepAnak.setToolTipText("Asesmen Awal Keperawatan Pasien Anak Rawat Jalan SUDAH diisi..!!!");
        }
        if (Sequel.cariInteger("select count(-1) from penilaian_awal_keperawatan_ranap_neonatus where no_rawat='" + norawat + "'") == 0) {
            BtnAwalKepGeriatri.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/2620509_employee_job_note_seeker_unemployee_icon.png")));
            BtnAwalKepGeriatri.setToolTipText("Asesmen Awal Keperawatan Pasien Neonatus Rawat Jalan BELUM diisi..!!!");
        } else {
            BtnAwalKepGeriatri.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/verif.png")));
            BtnAwalKepGeriatri.setToolTipText("Asesmen Awal Keperawatan Pasien Neonatus Rawat Jalan SUDAH diisi..!!!");
        }
        if (Sequel.cariInteger("select count(-1) from transfer_pasien_antar_ruang where no_rawat='" + norawat + "'") == 0) {
            BtnTransferRuang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/1481002123_wheelchair.png")));
            BtnTransferRuang.setToolTipText("Lembar Transfer Pasien BELUM diisi..!!!");
        } else {
            BtnTransferRuang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/verif.png")));
            BtnTransferRuang.setToolTipText("Lembar Transfer Pasien SUDAH diisi..!!!");
        }
        if (Sequel.cariInteger("select count(-1) from resume_pasien where no_rawat='" + norawat + "'") == 0) {
            BtnResume.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/2620524_cv_employee_job_seeker_unemployee_icon.png")));
            BtnResume.setToolTipText("Resume Pasien BELUM diisi..!!!");
        } else {
            BtnResume.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/verif.png")));
            BtnResume.setToolTipText("Resume Pasien SUDAH diisi..!!!");
        }
        if (Sequel.cariInteger("select count(-1) from penilaian_lanjutan_resiko_jatuh_dewasa where no_rawat='" + norawat + "'") == 0) {
            BtnRisikoJatuh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/iconfinder_dialog-warning_118940.png")));
            BtnRisikoJatuh.setToolTipText("Risiko Jatuh Pasien BELUM diisi..!!!");
        } else {
            BtnRisikoJatuh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/verif.png")));
            BtnRisikoJatuh.setToolTipText("Risiko Jatuh Pasien SUDAH diisi..!!!");
        }
        if (Sequel.cariInteger("select count(-1) from penilaian_lanjutan_resiko_jatuh_anak where no_rawat='" + norawat + "'") == 0) {
            BtnRisikoJatuhAnak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/iconfinder_dialog-warning_118940.png")));
            BtnRisikoJatuhAnak.setToolTipText("Risiko Jatuh Pasien Anak BELUM diisi..!!!");
        } else {
            BtnRisikoJatuhAnak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/verif.png")));
            BtnRisikoJatuhAnak.setToolTipText("Risiko Jatuh Pasien Anak SUDAH diisi..!!!");
        }
        if (Sequel.cariInteger("select count(-1) from penilaian_lanjutan_resiko_jatuh_geriatri where no_rawat='" + norawat + "'") == 0) {
            BtnRisikoJatuhGeriatri.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/iconfinder_dialog-warning_118940.png")));
            BtnRisikoJatuhGeriatri.setToolTipText("Risiko Jatuh Geriatri BELUM diisi..!!!");
        } else {
            BtnRisikoJatuhGeriatri.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/verif.png")));
            BtnRisikoJatuhGeriatri.setToolTipText("Risiko Jatuh Geriatri SUDAH diisi..!!!");
        }
        if (Sequel.cariInteger("select count(-1) from penilaian_lanjutan_resiko_jatuh_lansia where no_rawat='" + norawat + "'") == 0) {
            BtnRisikoJatuhLansia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/iconfinder_dialog-warning_118940.png")));
            BtnRisikoJatuhLansia.setToolTipText("Risiko Jatuh Lansia BELUM diisi..!!!");
        } else {
            BtnRisikoJatuhLansia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/verif.png")));
            BtnRisikoJatuhLansia.setToolTipText("Risiko Jatuh Lansia SUDAH diisi..!!!");
        }
        if (Sequel.cariInteger("select count(-1) from skrining_tbc where no_rawat='" + norawat + "'") == 0) {
            BtnSkriningTB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/6009767_avatar_healthcare_male_mask_medical_icon.png")));
            BtnSkriningTB.setToolTipText("Skrining TBC BELUM diisi..!!!");
        } else {
            BtnSkriningTB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/verif.png")));
            BtnSkriningTB.setToolTipText("Skrining TBC SUDAH diisi..!!!");
        }
        if (Sequel.cariInteger("select count(-1) from bridging_sep where no_rawat='" + norawat + "'") == 0) {
            BtnDataSep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/bpjs.png")));
            BtnDataSep.setToolTipText("SEP Pasien BELUM diisi..!!!");
        } else {
            BtnDataSep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/verif.png")));
            BtnDataSep.setToolTipText("SEP Pasien SUDAH diisi..!!!");
        }
        if (Sequel.cariInteger("select count(-1) from diagnosa_pasien where no_rawat='" + norawat + "'") == 0) {
            BtnDiagnosa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/health.png")));
            BtnDiagnosa.setToolTipText("Diagnosa Pasien BELUM diisi..!!!");
        } else {
            BtnDiagnosa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/verif.png")));
            BtnDiagnosa.setToolTipText("Diagnosa Pasien SUDAH diisi..!!!");
        }
    }
}
