package rekammedis;
import bridging.BPJSDataSEP;
import bridging.BPJSSuratKontrol;
import fungsi.koneksiDB;
import fungsi.sekuel;
import fungsi.validasi;
import fungsi.akses;
import java.awt.Cursor;
import java.awt.Desktop;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.text.Document;
import javax.swing.text.html.HTMLEditorKit;
import javax.swing.text.html.StyleSheet;
import kepegawaian.DlgCariDokter;
import kepegawaian.DlgCariPetugas;
import laporan.DlgDiagnosaPenyakit;
import rekammedis.RMDataResumePasien;
import rekammedis.RMPenilaianAwalKeperawatanBayiAnak;
import rekammedis.RMPenilaianAwalKeperawatanKebidanan;
import rekammedis.RMPenilaianAwalKeperawatanRalan;
import rekammedis.RMPenilaianAwalKeperawatanRalanGeriatri;
import rekammedis.RMPenilaianLanjutanRisikoJatuhAnak;
import rekammedis.RMPenilaianLanjutanRisikoJatuhDewasa;
import rekammedis.RMPenilaianLanjutanRisikoJatuhGeriatri;
import rekammedis.RMPenilaianLanjutanRisikoJatuhLansia;
import rekammedis.RMSkriningTBC;
import rekammedis.RMTransferPasienAntarRuang;

public class DlgERMIGD extends javax.swing.JDialog {
    private sekuel Sequel=new sekuel();
    private validasi Valid=new validasi();
    private Connection koneksi=koneksiDB.condb();
    private PreparedStatement ps,ps2;
    private ResultSet rs,rs2;
    private int i=0,x = 0;
    private DlgCariPetugas petugas=new DlgCariPetugas(null,false);
    private DlgCariDokter dokter=new DlgCariDokter(null,false);
    private String stts = "", kdkamar = "", gedung = "",kmr="",variabel="";
    
    /** Creates new form DlgProgramStudi
     * @param parent
     * @param modal */
    public DlgERMIGD(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        petugas.addWindowListener(new WindowListener() {
            @Override
            public void windowOpened(WindowEvent e) {}
            @Override
            public void windowClosing(WindowEvent e) {}
            @Override
            public void windowClosed(WindowEvent e) {
                if(petugas.getTable().getSelectedRow()!= -1){ 
                    if(i==1){
                        KdPetugas.setText(petugas.getTable().getValueAt(petugas.getTable().getSelectedRow(),0).toString());
                        NmPetugas.setText(petugas.getTable().getValueAt(petugas.getTable().getSelectedRow(),1).toString());  
                    }else{
                        KdPetugas2.setText(petugas.getTable().getValueAt(petugas.getTable().getSelectedRow(),0).toString());
                        NmPetugas2.setText(petugas.getTable().getValueAt(petugas.getTable().getSelectedRow(),1).toString());  
                    }
                         
                }              
            }
            @Override
            public void windowIconified(WindowEvent e) {}
            @Override
            public void windowDeiconified(WindowEvent e) {}
            @Override
            public void windowActivated(WindowEvent e) {}
            @Override
            public void windowDeactivated(WindowEvent e) {}
        });
        
        dokter.addWindowListener(new WindowListener() {
            @Override
            public void windowOpened(WindowEvent e) {}
            @Override
            public void windowClosing(WindowEvent e) {}
            @Override
            public void windowClosed(WindowEvent e) {
                if(dokter.getTable().getSelectedRow()!= -1){ 
                    KdDPJP.setText(dokter.getTable().getValueAt(dokter.getTable().getSelectedRow(),0).toString());
                    NmDPJP.setText(dokter.getTable().getValueAt(dokter.getTable().getSelectedRow(),1).toString());  
                }              
            }
            @Override
            public void windowIconified(WindowEvent e) {}
            @Override
            public void windowDeiconified(WindowEvent e) {}
            @Override
            public void windowActivated(WindowEvent e) {}
            @Override
            public void windowDeactivated(WindowEvent e) {}
        });
    }
    private Dimension screen=Toolkit.getDefaultToolkit().getScreenSize();

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        WindowDPJPranap = new javax.swing.JDialog();
        internalFrame15 = new widget.InternalFrame();
        KdDPJP = new widget.TextBox();
        NmDPJP = new widget.TextBox();
        btnDPJP = new widget.Button();
        KdPetugas = new widget.TextBox();
        NmPetugas = new widget.TextBox();
        KdPetugas2 = new widget.TextBox();
        NmPetugas2 = new widget.TextBox();
        internalFrame1 = new widget.InternalFrame();
        internalFrame4 = new widget.InternalFrame();
        jLabel3 = new widget.Label();
        TNoRW = new widget.TextBox();
        TNoRM = new widget.TextBox();
        TNmPasien = new widget.TextBox();
        jLabel13 = new widget.Label();
        jLabel4 = new widget.Label();
        TtglMasuk = new widget.TextBox();
        NoRawat = new widget.TextBox();
        NoSEP = new widget.TextBox();
        NoKartu = new widget.TextBox();
        NoRM = new widget.TextBox();
        NmPasien = new widget.TextBox();
        TabRekamMedis = new javax.swing.JTabbedPane();
        scrollInput = new widget.ScrollPane();
        FormInput = new widget.PanelBiasa();
        BtnAwalMedisIGD = new widget.ButtonBig();
        BtnAwalMedisIGDPsikiatri = new widget.ButtonBig();
        BtnAwalKeperawatanIGD = new widget.ButtonBig();
        BtnAwalKebidanan = new widget.ButtonBig();
        BtnTriaseIGD = new widget.ButtonBig();
        BtnPengkajianKeracunan = new widget.ButtonBig();
        BtnPengkajianRestrain = new widget.ButtonBig();
        BtnPemantauanPEWSAnak = new widget.ButtonBig();
        BtnPemantauanPEWSDewasa = new widget.ButtonBig();
        BtnTransferRuang = new widget.ButtonBig();
        BtnDiagnosa = new widget.ButtonBig();
        scrollInput1 = new widget.ScrollPane();
        FormInput1 = new widget.PanelBiasa();
        panelisi1 = new widget.panelisi();
        label9 = new widget.Label();
        BtnRefres = new widget.Button();
        BtnKeluar = new widget.Button();

        WindowDPJPranap.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        WindowDPJPranap.setName("WindowDPJPranap"); // NOI18N
        WindowDPJPranap.setUndecorated(true);
        WindowDPJPranap.setResizable(false);

        internalFrame15.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255), 3), "::[ DPJP Rawat Inap ]::", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        internalFrame15.setName("internalFrame15"); // NOI18N
        internalFrame15.setWarnaBawah(new java.awt.Color(245, 250, 240));
        internalFrame15.setLayout(null);

        KdDPJP.setEditable(false);
        KdDPJP.setForeground(new java.awt.Color(0, 0, 0));
        KdDPJP.setName("KdDPJP"); // NOI18N
        internalFrame15.add(KdDPJP);
        KdDPJP.setBounds(81, 32, 100, 23);

        NmDPJP.setEditable(false);
        NmDPJP.setForeground(new java.awt.Color(0, 0, 0));
        NmDPJP.setName("NmDPJP"); // NOI18N
        internalFrame15.add(NmDPJP);
        NmDPJP.setBounds(183, 32, 380, 23);

        btnDPJP.setForeground(new java.awt.Color(0, 0, 0));
        btnDPJP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/190.png"))); // NOI18N
        btnDPJP.setMnemonic('7');
        btnDPJP.setToolTipText("ALt+7");
        btnDPJP.setName("btnDPJP"); // NOI18N
        btnDPJP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDPJPActionPerformed(evt);
            }
        });
        internalFrame15.add(btnDPJP);
        btnDPJP.setBounds(565, 32, 28, 23);

        KdPetugas.setEditable(false);
        KdPetugas.setForeground(new java.awt.Color(0, 0, 0));
        KdPetugas.setName("KdPetugas"); // NOI18N
        internalFrame15.add(KdPetugas);
        KdPetugas.setBounds(81, 32, 100, 23);

        NmPetugas.setEditable(false);
        NmPetugas.setForeground(new java.awt.Color(0, 0, 0));
        NmPetugas.setName("NmPetugas"); // NOI18N
        internalFrame15.add(NmPetugas);
        NmPetugas.setBounds(81, 32, 100, 23);

        KdPetugas2.setEditable(false);
        KdPetugas2.setForeground(new java.awt.Color(0, 0, 0));
        KdPetugas2.setName("KdPetugas2"); // NOI18N
        internalFrame15.add(KdPetugas2);
        KdPetugas2.setBounds(81, 32, 100, 23);

        NmPetugas2.setEditable(false);
        NmPetugas2.setForeground(new java.awt.Color(0, 0, 0));
        NmPetugas2.setName("NmPetugas2"); // NOI18N
        internalFrame15.add(NmPetugas2);
        NmPetugas2.setBounds(81, 32, 100, 23);

        WindowDPJPranap.getContentPane().add(internalFrame15, java.awt.BorderLayout.CENTER);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        internalFrame1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 245, 235)), "::[ ERM INAP ]::", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(50, 50, 50))); // NOI18N
        internalFrame1.setName("internalFrame1"); // NOI18N
        internalFrame1.setLayout(new java.awt.BorderLayout(1, 1));

        internalFrame4.setName("internalFrame4"); // NOI18N
        internalFrame4.setPreferredSize(new java.awt.Dimension(12, 100));
        internalFrame4.setLayout(null);

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("NoRawat/RM :");
        jLabel3.setName("jLabel3"); // NOI18N
        internalFrame4.add(jLabel3);
        jLabel3.setBounds(0, 10, 103, 23);

        TNoRW.setEditable(false);
        TNoRW.setForeground(new java.awt.Color(0, 0, 0));
        TNoRW.setName("TNoRW"); // NOI18N
        internalFrame4.add(TNoRW);
        TNoRW.setBounds(107, 10, 122, 23);

        TNoRM.setEditable(false);
        TNoRM.setForeground(new java.awt.Color(0, 0, 0));
        TNoRM.setName("TNoRM"); // NOI18N
        internalFrame4.add(TNoRM);
        TNoRM.setBounds(230, 10, 70, 23);

        TNmPasien.setEditable(false);
        TNmPasien.setForeground(new java.awt.Color(0, 0, 0));
        TNmPasien.setName("TNmPasien"); // NOI18N
        internalFrame4.add(TNmPasien);
        TNmPasien.setBounds(110, 40, 280, 23);

        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Nama :");
        jLabel13.setName("jLabel13"); // NOI18N
        internalFrame4.add(jLabel13);
        jLabel13.setBounds(0, 38, 103, 23);

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Tanggal Regis :");
        jLabel4.setName("jLabel4"); // NOI18N
        internalFrame4.add(jLabel4);
        jLabel4.setBounds(0, 66, 103, 23);

        TtglMasuk.setEditable(false);
        TtglMasuk.setForeground(new java.awt.Color(0, 0, 0));
        TtglMasuk.setName("TtglMasuk"); // NOI18N
        internalFrame4.add(TtglMasuk);
        TtglMasuk.setBounds(107, 66, 280, 23);

        NoRawat.setEditable(false);
        NoRawat.setForeground(new java.awt.Color(0, 0, 0));
        NoRawat.setName("NoRawat"); // NOI18N
        internalFrame4.add(NoRawat);
        NoRawat.setBounds(107, 10, 122, 23);

        NoSEP.setEditable(false);
        NoSEP.setForeground(new java.awt.Color(0, 0, 0));
        NoSEP.setName("NoSEP"); // NOI18N
        internalFrame4.add(NoSEP);
        NoSEP.setBounds(107, 10, 122, 23);

        NoKartu.setEditable(false);
        NoKartu.setForeground(new java.awt.Color(0, 0, 0));
        NoKartu.setName("NoKartu"); // NOI18N
        internalFrame4.add(NoKartu);
        NoKartu.setBounds(107, 10, 122, 23);

        NoRM.setEditable(false);
        NoRM.setForeground(new java.awt.Color(0, 0, 0));
        NoRM.setName("NoRM"); // NOI18N
        internalFrame4.add(NoRM);
        NoRM.setBounds(107, 10, 122, 23);

        NmPasien.setEditable(false);
        NmPasien.setForeground(new java.awt.Color(0, 0, 0));
        NmPasien.setName("NmPasien"); // NOI18N
        internalFrame4.add(NmPasien);
        NmPasien.setBounds(107, 10, 122, 23);

        internalFrame1.add(internalFrame4, java.awt.BorderLayout.PAGE_START);

        TabRekamMedis.setBackground(new java.awt.Color(255, 255, 254));
        TabRekamMedis.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        TabRekamMedis.setName("TabRekamMedis"); // NOI18N
        TabRekamMedis.setPreferredSize(new java.awt.Dimension(270, 106));

        scrollInput.setName("scrollInput"); // NOI18N
        scrollInput.setPreferredSize(new java.awt.Dimension(102, 557));

        FormInput.setBackground(new java.awt.Color(255, 255, 255));
        FormInput.setBorder(null);
        FormInput.setName("FormInput"); // NOI18N
        FormInput.setPreferredSize(new java.awt.Dimension(870, 834));
        FormInput.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 8, 25));

        BtnAwalMedisIGD.setForeground(new java.awt.Color(0, 0, 0));
        BtnAwalMedisIGD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/doctor2.png"))); // NOI18N
        BtnAwalMedisIGD.setText("Asesmen Awal Medis IGD");
        BtnAwalMedisIGD.setIconTextGap(0);
        BtnAwalMedisIGD.setName("BtnAwalMedisIGD"); // NOI18N
        BtnAwalMedisIGD.setPreferredSize(new java.awt.Dimension(200, 90));
        BtnAwalMedisIGD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAwalMedisIGDActionPerformed(evt);
            }
        });
        FormInput.add(BtnAwalMedisIGD);

        BtnAwalMedisIGDPsikiatri.setForeground(new java.awt.Color(0, 0, 0));
        BtnAwalMedisIGDPsikiatri.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/doctor2.png"))); // NOI18N
        BtnAwalMedisIGDPsikiatri.setText("Asesmen Awal Medis IGD Psikiatri");
        BtnAwalMedisIGDPsikiatri.setIconTextGap(0);
        BtnAwalMedisIGDPsikiatri.setName("BtnAwalMedisIGDPsikiatri"); // NOI18N
        BtnAwalMedisIGDPsikiatri.setPreferredSize(new java.awt.Dimension(200, 90));
        BtnAwalMedisIGDPsikiatri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAwalMedisIGDPsikiatriActionPerformed(evt);
            }
        });
        FormInput.add(BtnAwalMedisIGDPsikiatri);

        BtnAwalKeperawatanIGD.setForeground(new java.awt.Color(0, 0, 0));
        BtnAwalKeperawatanIGD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/1481002413_surgeon.png"))); // NOI18N
        BtnAwalKeperawatanIGD.setText("Asesmen Awal Keperawatan");
        BtnAwalKeperawatanIGD.setIconTextGap(0);
        BtnAwalKeperawatanIGD.setName("BtnAwalKeperawatanIGD"); // NOI18N
        BtnAwalKeperawatanIGD.setPreferredSize(new java.awt.Dimension(200, 90));
        BtnAwalKeperawatanIGD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAwalKeperawatanIGDActionPerformed(evt);
            }
        });
        FormInput.add(BtnAwalKeperawatanIGD);

        BtnAwalKebidanan.setForeground(new java.awt.Color(0, 0, 0));
        BtnAwalKebidanan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/1481002413_surgeon.png"))); // NOI18N
        BtnAwalKebidanan.setText("Asesmen Awal Kebidanan");
        BtnAwalKebidanan.setIconTextGap(0);
        BtnAwalKebidanan.setName("BtnAwalKebidanan"); // NOI18N
        BtnAwalKebidanan.setPreferredSize(new java.awt.Dimension(200, 90));
        BtnAwalKebidanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAwalKebidananActionPerformed(evt);
            }
        });
        FormInput.add(BtnAwalKebidanan);

        BtnTriaseIGD.setForeground(new java.awt.Color(0, 0, 0));
        BtnTriaseIGD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/8960611_hospitals_hospital_building_medic_health_icon.png"))); // NOI18N
        BtnTriaseIGD.setText("Triase Gawat Darurat");
        BtnTriaseIGD.setIconTextGap(0);
        BtnTriaseIGD.setName("BtnTriaseIGD"); // NOI18N
        BtnTriaseIGD.setPreferredSize(new java.awt.Dimension(200, 90));
        BtnTriaseIGD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTriaseIGDActionPerformed(evt);
            }
        });
        FormInput.add(BtnTriaseIGD);

        BtnPengkajianKeracunan.setForeground(new java.awt.Color(0, 0, 0));
        BtnPengkajianKeracunan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/5986162_disease_health_injury_medical_numb_icon.png"))); // NOI18N
        BtnPengkajianKeracunan.setText("Pengkajian Pasien Keracunan");
        BtnPengkajianKeracunan.setIconTextGap(0);
        BtnPengkajianKeracunan.setName("BtnPengkajianKeracunan"); // NOI18N
        BtnPengkajianKeracunan.setPreferredSize(new java.awt.Dimension(200, 90));
        BtnPengkajianKeracunan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPengkajianKeracunanActionPerformed(evt);
            }
        });
        FormInput.add(BtnPengkajianKeracunan);

        BtnPengkajianRestrain.setForeground(new java.awt.Color(0, 0, 0));
        BtnPengkajianRestrain.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/5859959_blood_health_heart_hypertension_medical_icon.png"))); // NOI18N
        BtnPengkajianRestrain.setText("Pengkajian Restrain");
        BtnPengkajianRestrain.setIconTextGap(0);
        BtnPengkajianRestrain.setName("BtnPengkajianRestrain"); // NOI18N
        BtnPengkajianRestrain.setPreferredSize(new java.awt.Dimension(200, 90));
        BtnPengkajianRestrain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPengkajianRestrainActionPerformed(evt);
            }
        });
        FormInput.add(BtnPengkajianRestrain);

        BtnPemantauanPEWSAnak.setForeground(new java.awt.Color(0, 0, 0));
        BtnPemantauanPEWSAnak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/7744788_mom_children_mothers day_mother_love_icon.png"))); // NOI18N
        BtnPemantauanPEWSAnak.setText("PEWS Anak");
        BtnPemantauanPEWSAnak.setIconTextGap(0);
        BtnPemantauanPEWSAnak.setName("BtnPemantauanPEWSAnak"); // NOI18N
        BtnPemantauanPEWSAnak.setPreferredSize(new java.awt.Dimension(200, 90));
        BtnPemantauanPEWSAnak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPemantauanPEWSAnakActionPerformed(evt);
            }
        });
        FormInput.add(BtnPemantauanPEWSAnak);

        BtnPemantauanPEWSDewasa.setForeground(new java.awt.Color(0, 0, 0));
        BtnPemantauanPEWSDewasa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/5928521_disease_fever_high_symptom_temperature_icon.png"))); // NOI18N
        BtnPemantauanPEWSDewasa.setText("PEWS Dewasa");
        BtnPemantauanPEWSDewasa.setIconTextGap(0);
        BtnPemantauanPEWSDewasa.setName("BtnPemantauanPEWSDewasa"); // NOI18N
        BtnPemantauanPEWSDewasa.setPreferredSize(new java.awt.Dimension(200, 90));
        BtnPemantauanPEWSDewasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPemantauanPEWSDewasaActionPerformed(evt);
            }
        });
        FormInput.add(BtnPemantauanPEWSDewasa);

        BtnTransferRuang.setForeground(new java.awt.Color(0, 0, 0));
        BtnTransferRuang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/6009596_case_coronavirus_covid19_hospital_patient_icon.png"))); // NOI18N
        BtnTransferRuang.setText("Transfer Pasien");
        BtnTransferRuang.setIconTextGap(0);
        BtnTransferRuang.setName("BtnTransferRuang"); // NOI18N
        BtnTransferRuang.setPreferredSize(new java.awt.Dimension(200, 90));
        BtnTransferRuang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTransferRuangActionPerformed(evt);
            }
        });
        FormInput.add(BtnTransferRuang);

        BtnDiagnosa.setForeground(new java.awt.Color(0, 0, 0));
        BtnDiagnosa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/health.png"))); // NOI18N
        BtnDiagnosa.setText("Diagnosa");
        BtnDiagnosa.setIconTextGap(0);
        BtnDiagnosa.setName("BtnDiagnosa"); // NOI18N
        BtnDiagnosa.setPreferredSize(new java.awt.Dimension(200, 90));
        BtnDiagnosa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDiagnosaActionPerformed(evt);
            }
        });
        FormInput.add(BtnDiagnosa);

        scrollInput.setViewportView(FormInput);

        TabRekamMedis.addTab("ERM IGD", scrollInput);

        scrollInput1.setName("scrollInput1"); // NOI18N
        scrollInput1.setPreferredSize(new java.awt.Dimension(102, 557));

        FormInput1.setBackground(new java.awt.Color(255, 255, 255));
        FormInput1.setBorder(null);
        FormInput1.setName("FormInput1"); // NOI18N
        FormInput1.setPreferredSize(new java.awt.Dimension(870, 834));
        FormInput1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 8, 25));
        scrollInput1.setViewportView(FormInput1);

        TabRekamMedis.addTab("", scrollInput1);

        internalFrame1.add(TabRekamMedis, java.awt.BorderLayout.CENTER);

        panelisi1.setName("panelisi1"); // NOI18N
        panelisi1.setPreferredSize(new java.awt.Dimension(100, 56));
        panelisi1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 9));

        label9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label9.setName("label9"); // NOI18N
        label9.setPreferredSize(new java.awt.Dimension(20, 30));
        panelisi1.add(label9);

        BtnRefres.setForeground(new java.awt.Color(0, 0, 0));
        BtnRefres.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/42a.png"))); // NOI18N
        BtnRefres.setMnemonic('R');
        BtnRefres.setText("Refresh Rekam Medis");
        BtnRefres.setToolTipText("Alt+R");
        BtnRefres.setName("BtnRefres"); // NOI18N
        BtnRefres.setPreferredSize(new java.awt.Dimension(186, 30));
        BtnRefres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRefresActionPerformed(evt);
            }
        });
        panelisi1.add(BtnRefres);

        BtnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/exit.png"))); // NOI18N
        BtnKeluar.setMnemonic('K');
        BtnKeluar.setText("Keluar");
        BtnKeluar.setToolTipText("Alt+K");
        BtnKeluar.setName("BtnKeluar"); // NOI18N
        BtnKeluar.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKeluarActionPerformed(evt);
            }
        });
        BtnKeluar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnKeluarKeyPressed(evt);
            }
        });
        panelisi1.add(BtnKeluar);

        internalFrame1.add(panelisi1, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(internalFrame1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
/*
private void KdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TKdKeyPressed
    Valid.pindah(evt,BtnCari,Nm);
}//GEN-LAST:event_TKdKeyPressed
*/

    private void BtnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKeluarActionPerformed
        dispose();
    }//GEN-LAST:event_BtnKeluarActionPerformed

    private void BtnKeluarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnKeluarKeyPressed
        TNoRW.setText("");
        TNoRM.setText("");
        TNmPasien.setText("");
        stts = "";
        kdkamar = "";        
        gedung = "";
        TtglMasuk.setText("");
        dispose();
    }//GEN-LAST:event_BtnKeluarKeyPressed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        isCek();
    }//GEN-LAST:event_formWindowOpened

    private void BtnRefresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRefresActionPerformed
        tombolCek(TNoRW.getText());
    }//GEN-LAST:event_BtnRefresActionPerformed

    private void btnDPJPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDPJPActionPerformed
        akses.setform("DlgERMIGD");
        dokter.emptTeks();
        dokter.isCek();
        dokter.setSize(internalFrame1.getWidth(), internalFrame1.getHeight());
        dokter.setLocationRelativeTo(internalFrame1);
        dokter.setVisible(true);
    }//GEN-LAST:event_btnDPJPActionPerformed

    private void BtnAwalKeperawatanIGDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAwalKeperawatanIGDActionPerformed
        if (TNoRW.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, Silahkan anda pilih dulu salah satu datanya pada tabel...!!!");
        } else {
            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            akses.setform("DlgERMIGD");
            RMPenilaianAwalKeperawatanIGD form = new RMPenilaianAwalKeperawatanIGD(null, false);
            form.emptTeks();
            form.isCek();
            form.setNoRm2(TNoRW.getText());
            form.setSize(internalFrame1.getWidth(), internalFrame1.getHeight());
            form.setLocationRelativeTo(internalFrame1);
            form.setVisible(true);
            this.setCursor(Cursor.getDefaultCursor());
        }// TODO add your handling code here:
    }//GEN-LAST:event_BtnAwalKeperawatanIGDActionPerformed

    private void BtnAwalKebidananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAwalKebidananActionPerformed
        if (TNoRW.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, Silahkan anda pilih dulu salah satu datanya pada tabel...!!!");
        } else {
            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            akses.setform("DlgERMIGD");
            RMPenilaianAwalKeperawatanKebidanan form = new RMPenilaianAwalKeperawatanKebidanan (null, false);
            form.emptTeks();
            form.isCek();
            form.setNoRm2(TNoRW.getText());
            form.setSize(internalFrame1.getWidth(), internalFrame1.getHeight());
            form.setLocationRelativeTo(internalFrame1);
            form.setVisible(true);
            this.setCursor(Cursor.getDefaultCursor());
        }// TODO add your handling code here:
    }//GEN-LAST:event_BtnAwalKebidananActionPerformed

    private void BtnDiagnosaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDiagnosaActionPerformed
        if (TNoRW.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, Silahkan anda pilih dulu salah satu datanya pada tabel...!!!");
        } else {
                this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            akses.setform("DlgERMIGD");
            DlgDiagnosaPenyakit form = new DlgDiagnosaPenyakit(null, false);
            form.isCek();
            form.setPasien(TNoRW.getText());
            form.setSize(internalFrame1.getWidth(), internalFrame1.getHeight());
            form.setLocationRelativeTo(internalFrame1);
            form.setVisible(true);
            this.setCursor(Cursor.getDefaultCursor());
        }// TODO add your handling code here:
    }//GEN-LAST:event_BtnDiagnosaActionPerformed

    private void BtnAwalMedisIGDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAwalMedisIGDActionPerformed
        if (TNoRW.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, Silahkan anda pilih dulu salah satu datanya pada tabel...!!!");
        } else {
            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            akses.setform("DlgERMIGD");
            RMPenilaianAwalMedisIGD form = new RMPenilaianAwalMedisIGD(null, false);
            form.emptTeks();
            form.isCek();
            form.setNoRm2(TNoRW.getText());
            form.setSize(internalFrame1.getWidth(), internalFrame1.getHeight());
            form.setLocationRelativeTo(internalFrame1);
            form.setVisible(true);
            this.setCursor(Cursor.getDefaultCursor());
        }// TODO add your handling code here:
    }//GEN-LAST:event_BtnAwalMedisIGDActionPerformed

    private void BtnTriaseIGDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTriaseIGDActionPerformed
        if (TNoRW.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, Silahkan anda pilih dulu salah satu datanya pada tabel...!!!");
        } else {
            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            akses.setform("DlgERMIGD");
            RMTriaseIGD form = new RMTriaseIGD(null, false);
            form.emptTeks();
            form.isCek();
            form.setNoRm2(TNoRW.getText(),TNoRM.getText(),TNmPasien.getText());
            form.setSize(internalFrame1.getWidth(), internalFrame1.getHeight());
            form.setLocationRelativeTo(internalFrame1);
            form.setVisible(true);
            this.setCursor(Cursor.getDefaultCursor());
        }
    }//GEN-LAST:event_BtnTriaseIGDActionPerformed

    private void BtnAwalMedisIGDPsikiatriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAwalMedisIGDPsikiatriActionPerformed
        if (TNoRW.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, Silahkan anda pilih dulu salah satu datanya pada tabel...!!!");
        } else {
            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            akses.setform("DlgERMIGD");
            RMPenilaianAwalMedisIGDPsikiatri form = new RMPenilaianAwalMedisIGDPsikiatri(null, false);
            form.emptTeks();
            form.isCek();
            form.setNoRm2(TNoRW.getText());
            form.setSize(internalFrame1.getWidth(), internalFrame1.getHeight());
            form.setLocationRelativeTo(internalFrame1);
            form.setVisible(true);
            this.setCursor(Cursor.getDefaultCursor());
        }// TODO add your handling code here:
    }//GEN-LAST:event_BtnAwalMedisIGDPsikiatriActionPerformed

    private void BtnPengkajianKeracunanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPengkajianKeracunanActionPerformed
        if (TNoRW.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, Silahkan anda pilih dulu salah satu datanya pada tabel...!!!");
        } else {
           akses.setform("DlgERMIGD");
           RMPenilaianPasienKeracunan form = new RMPenilaianPasienKeracunan(null, false);
           form.emptTeks();
           form.isCek();
           form.setSize(internalFrame1.getWidth(),internalFrame1.getHeight());
           form.setLocationRelativeTo(internalFrame1);
           form.setVisible(true);
           form.setNoRm2(TNoRW.getText());
           this.setCursor(Cursor.getDefaultCursor());
        }// TODO add your handling code here:
    }//GEN-LAST:event_BtnPengkajianKeracunanActionPerformed

    private void BtnPengkajianRestrainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPengkajianRestrainActionPerformed
        if (TNoRW.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, Silahkan anda pilih dulu salah satu datanya pada tabel...!!!");
        } else {
           akses.setform("DlgERMIGD");
           RMPengkajianRestrain form = new RMPengkajianRestrain(null, false);
           form.emptTeks();
           form.isCek();
           form.setSize(internalFrame1.getWidth(),internalFrame1.getHeight());
           form.setLocationRelativeTo(internalFrame1);
           form.setVisible(true);
           form.setNoRm2(TNoRW.getText());
           this.setCursor(Cursor.getDefaultCursor());
        }// TODO add your handling code here:
    }//GEN-LAST:event_BtnPengkajianRestrainActionPerformed

    private void BtnPemantauanPEWSAnakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPemantauanPEWSAnakActionPerformed
        if (TNoRW.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, Silahkan anda pilih dulu salah satu datanya pada tabel...!!!");
        } else {
           akses.setform("DlgERMIGD");
           RMPemantauanPEWS form = new RMPemantauanPEWS(null, false);
           form.emptTeks();
           form.isCek();
           form.setSize(internalFrame1.getWidth(),internalFrame1.getHeight());
           form.setLocationRelativeTo(internalFrame1);
           form.setVisible(true);
           form.setNoRm2(TNoRW.getText());
           this.setCursor(Cursor.getDefaultCursor());
        }// TODO add your handling code here:
    }//GEN-LAST:event_BtnPemantauanPEWSAnakActionPerformed

    private void BtnPemantauanPEWSDewasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPemantauanPEWSDewasaActionPerformed
        if (TNoRW.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, Silahkan anda pilih dulu salah satu datanya pada tabel...!!!");
        } else {
            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            akses.setform("DlgERMIGD");
            RMPemantauanEWSD form = new RMPemantauanEWSD(null, false);
            form.emptTeks();
            form.isCek();
            form.setNoRm2(TNoRW.getText());
            form.setSize(internalFrame1.getWidth(), internalFrame1.getHeight());
            form.setLocationRelativeTo(internalFrame1);
            form.setVisible(true);
            this.setCursor(Cursor.getDefaultCursor());
        }// TODO add your handling code here:
    }//GEN-LAST:event_BtnPemantauanPEWSDewasaActionPerformed

    private void BtnTransferRuangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTransferRuangActionPerformed
        if (TNoRW.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, Silahkan anda pilih dulu salah satu datanya pada tabel...!!!");
        } else {
            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            akses.setform("DlgERMIGD");
            RMTransferPasienAntarRuang form = new RMTransferPasienAntarRuang(null, false);
            form.emptTeks();
            form.isCek();
            form.setNoRm2(TNoRW.getText());
            form.setSize(internalFrame1.getWidth(), internalFrame1.getHeight());
            form.setLocationRelativeTo(internalFrame1);
            form.setVisible(true);
            this.setCursor(Cursor.getDefaultCursor());
        }// TODO add your handling code here:
    }//GEN-LAST:event_BtnTransferRuangActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            DlgERMIGD dialog = new DlgERMIGD(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private widget.ButtonBig BtnAwalKebidanan;
    private widget.ButtonBig BtnAwalKeperawatanIGD;
    private widget.ButtonBig BtnAwalMedisIGD;
    private widget.ButtonBig BtnAwalMedisIGDPsikiatri;
    private widget.ButtonBig BtnDiagnosa;
    private widget.Button BtnKeluar;
    private widget.ButtonBig BtnPemantauanPEWSAnak;
    private widget.ButtonBig BtnPemantauanPEWSDewasa;
    private widget.ButtonBig BtnPengkajianKeracunan;
    private widget.ButtonBig BtnPengkajianRestrain;
    private widget.Button BtnRefres;
    private widget.ButtonBig BtnTransferRuang;
    private widget.ButtonBig BtnTriaseIGD;
    private widget.PanelBiasa FormInput;
    private widget.PanelBiasa FormInput1;
    private widget.TextBox KdDPJP;
    private widget.TextBox KdPetugas;
    private widget.TextBox KdPetugas2;
    private widget.TextBox NmDPJP;
    private widget.TextBox NmPasien;
    private widget.TextBox NmPetugas;
    private widget.TextBox NmPetugas2;
    private widget.TextBox NoKartu;
    private widget.TextBox NoRM;
    private widget.TextBox NoRawat;
    private widget.TextBox NoSEP;
    private widget.TextBox TNmPasien;
    private widget.TextBox TNoRM;
    private widget.TextBox TNoRW;
    private javax.swing.JTabbedPane TabRekamMedis;
    private widget.TextBox TtglMasuk;
    private javax.swing.JDialog WindowDPJPranap;
    private widget.Button btnDPJP;
    private widget.InternalFrame internalFrame1;
    private widget.InternalFrame internalFrame15;
    private widget.InternalFrame internalFrame4;
    private widget.Label jLabel13;
    private widget.Label jLabel3;
    private widget.Label jLabel4;
    private widget.Label label9;
    private widget.panelisi panelisi1;
    private widget.ScrollPane scrollInput;
    private widget.ScrollPane scrollInput1;
    // End of variables declaration//GEN-END:variables

    
    private void isCek() {
        BtnAwalMedisIGD.setEnabled(akses.getpenilaian_awal_medis_igd());
        BtnAwalMedisIGDPsikiatri.setEnabled(akses.getpenilaian_medis_ralan_gawat_darurat_psikiatri());
        BtnAwalKeperawatanIGD.setEnabled(akses.getpenilaian_awal_keperawatan_igd());
        BtnAwalKebidanan.setEnabled(akses.getpenilaian_awal_keperawatan_kebidanan());
        BtnDiagnosa.setEnabled(akses.getdiagnosa_pasien());
        BtnTriaseIGD.setEnabled(akses.getdata_triase_igd());
        BtnPengkajianKeracunan.setEnabled(akses.getpenilaian_pasien_keracunan());
        BtnPengkajianRestrain.setEnabled(akses.getpengkajian_restrain());
        BtnPemantauanPEWSAnak.setEnabled(akses.getpemantauan_pews_anak());
        BtnPemantauanPEWSDewasa.setEnabled(akses.getpemantauan_pews_dewasa());
        BtnTransferRuang.setEnabled(akses.gettransfer_pasien_antar_ruang());
    }
    
    public void setData(String norw, String norm, String nmpasien, 
            String ralan, String noreg, String TglINDONESIA) {
       TNoRW.setText(norw);
       TNoRM.setText(norm);
       TNmPasien.setText(nmpasien);
       TtglMasuk.setText(TglINDONESIA);
       tombolCek(norw);
    }
    
    private void tombolCek(String norawat) {
        if (Sequel.cariInteger("select count(-1) from penilaian_medis_igd where no_rawat='" + norawat + "'") == 0) {
            BtnAwalMedisIGD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/doctor2.png")));
            BtnAwalMedisIGD.setToolTipText("Asesmen Awal Medis IGD BELUM diisi..!!!");
        } else {
            BtnAwalMedisIGD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/verif.png")));
            BtnAwalMedisIGD.setToolTipText("Asesmen Awal Medis IGD SUDAH diisi..!!!");
        }
        if (Sequel.cariInteger("select count(-1) from penilaian_medis_ralan_gawat_darurat_psikiatri where no_rawat='" + norawat + "'") == 0) {
            BtnAwalMedisIGDPsikiatri.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/doctor2.png")));
            BtnAwalMedisIGDPsikiatri.setToolTipText("Asesmen Awal Medis IGD Psikiatri BELUM diisi..!!!");
        } else {
            BtnAwalMedisIGDPsikiatri.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/verif.png")));
            BtnAwalMedisIGDPsikiatri.setToolTipText("Asesmen Awal Medis IGD Psikiatri SUDAH diisi..!!!");
        }
        if (Sequel.cariInteger("select count(-1) from penilaian_awal_keperawatan_igd where no_rawat='" + norawat + "'") == 0) {
            BtnAwalKeperawatanIGD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/1481002413_surgeon.png")));
            BtnAwalKeperawatanIGD.setToolTipText("Asesmen Awal Keperawatan IGD BELUM diisi..!!!");
        } else {
            BtnAwalKeperawatanIGD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/verif.png")));
            BtnAwalKeperawatanIGD.setToolTipText("Asesmen Awal Keperawatan IGD SUDAH diisi..!!!");
        }
        if (Sequel.cariInteger("select count(-1) from penilaian_awal_keperawatan_kebidanan where no_rawat='" + norawat + "'") == 0) {
            BtnAwalKebidanan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/1481002413_surgeon.png")));
            BtnAwalKebidanan.setToolTipText("Asesmen Awal Kebidanan IGD BELUM diisi..!!!");
        } else {
            BtnAwalKebidanan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/verif.png")));
            BtnAwalKebidanan.setToolTipText("Asesmen Awal Kebidanan IGD SUDAH diisi..!!!");
        }
        if (Sequel.cariInteger("select count(-1) from data_triase_igd where no_rawat='" + norawat + "'") == 0) {
            BtnTriaseIGD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/8960611_hospitals_hospital_building_medic_health_icon.png")));
            BtnTriaseIGD.setToolTipText("Triase IGD BELUM diisi..!!!");
        } else {
            BtnTriaseIGD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/verif.png")));
            BtnTriaseIGD.setToolTipText("Triase IGD SUDAH diisi..!!!");
        }
        if (Sequel.cariInteger("select count(-1) from penilaian_pasien_keracunan where no_rawat='" + norawat + "'") == 0) {
            BtnPengkajianKeracunan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/5986162_disease_health_injury_medical_numb_icon.png")));
            BtnPengkajianKeracunan.setToolTipText("Pengkajian Pasien Keracunan BELUM diisi..!!!");
        } else {
            BtnPengkajianKeracunan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/verif.png")));
            BtnPengkajianKeracunan.setToolTipText("Pengkajian Pasien Keracunan SUDAH diisi..!!!");
        }
        if (Sequel.cariInteger("select count(-1) from pengkajian_restrain where no_rawat='" + norawat + "'") == 0) {
            BtnPengkajianRestrain.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/5859959_blood_health_heart_hypertension_medical_icon.png")));
            BtnPengkajianRestrain.setToolTipText("Pengkajian Restrain BELUM diisi..!!!");
        } else {
            BtnPengkajianRestrain.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/verif.png")));
            BtnPengkajianRestrain.setToolTipText("Pengkajian Restrain SUDAH diisi..!!!");
        }
        if (Sequel.cariInteger("select count(-1) from pemantauan_pews_anak where no_rawat='" + norawat + "'") == 0) {
            BtnPemantauanPEWSAnak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/7744788_mom_children_mothers day_mother_love_icon.png")));
            BtnPemantauanPEWSAnak.setToolTipText("Pemantauan WES Anak BELUM diisi..!!!");
        } else {
            BtnPemantauanPEWSAnak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/verif.png")));
            BtnPemantauanPEWSAnak.setToolTipText("Pemantauan WES Anak SUDAH diisi..!!!");
        }
        if (Sequel.cariInteger("select count(-1) from pemantauan_pews_dewasa where no_rawat='" + norawat + "'") == 0) {
            BtnPemantauanPEWSDewasa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/5928521_disease_fever_high_symptom_temperature_icon.png")));
            BtnPemantauanPEWSDewasa.setToolTipText("Pemantauan WES Dewasa BELUM diisi..!!!");
        } else {
            BtnPemantauanPEWSDewasa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/verif.png")));
            BtnPemantauanPEWSDewasa.setToolTipText("Pemantauan WES Dewasa SUDAH diisi..!!!");
        }
        if (Sequel.cariInteger("select count(-1) from transfer_pasien_antar_ruang where no_rawat='" + norawat + "'") == 0) {
            BtnTransferRuang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/6009596_case_coronavirus_covid19_hospital_patient_icon.png")));
            BtnTransferRuang.setToolTipText("Transfer Pasien BELUM diisi..!!!");
        } else {
            BtnTransferRuang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/verif.png")));
            BtnTransferRuang.setToolTipText("Transfer Pasien SUDAH diisi..!!!");
        }
        if (Sequel.cariInteger("select count(-1) from diagnosa_pasien where no_rawat='" + norawat + "'") == 0) {
            BtnDiagnosa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/health.png")));
            BtnDiagnosa.setToolTipText("Diagnosa Pasien BELUM diisi..!!!");
        } else {
            BtnDiagnosa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/verif.png")));
            BtnDiagnosa.setToolTipText("Diagnosa Pasien SUDAH diisi..!!!");
        }
    }
}
