package rekammedis;
import fungsi.koneksiDB;
import fungsi.sekuel;
import fungsi.validasi;
import fungsi.akses;
import java.awt.Cursor;
import java.awt.Desktop;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.text.Document;
import javax.swing.text.html.HTMLEditorKit;
import javax.swing.text.html.StyleSheet;
import kepegawaian.DlgCariDokter;
import kepegawaian.DlgCariPetugas;

public class DlgERM extends javax.swing.JDialog {
    private sekuel Sequel=new sekuel();
    private validasi Valid=new validasi();
    private Connection koneksi=koneksiDB.condb();
    private PreparedStatement ps,ps2;
    private ResultSet rs,rs2;
    private int i=0,x = 0;
    private DlgCariPetugas petugas=new DlgCariPetugas(null,false);
    private DlgCariDokter dokter=new DlgCariDokter(null,false);
    private String stts = "", kdkamar = "", gedung = "",kmr="";
    
    /** Creates new form DlgProgramStudi
     * @param parent
     * @param modal */
    public DlgERM(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        petugas.addWindowListener(new WindowListener() {
            @Override
            public void windowOpened(WindowEvent e) {}
            @Override
            public void windowClosing(WindowEvent e) {}
            @Override
            public void windowClosed(WindowEvent e) {
                if(petugas.getTable().getSelectedRow()!= -1){ 
                    if(i==1){
                        KdPetugas.setText(petugas.getTable().getValueAt(petugas.getTable().getSelectedRow(),0).toString());
                        NmPetugas.setText(petugas.getTable().getValueAt(petugas.getTable().getSelectedRow(),1).toString());  
                    }else{
                        KdPetugas2.setText(petugas.getTable().getValueAt(petugas.getTable().getSelectedRow(),0).toString());
                        NmPetugas2.setText(petugas.getTable().getValueAt(petugas.getTable().getSelectedRow(),1).toString());  
                    }
                         
                }              
            }
            @Override
            public void windowIconified(WindowEvent e) {}
            @Override
            public void windowDeiconified(WindowEvent e) {}
            @Override
            public void windowActivated(WindowEvent e) {}
            @Override
            public void windowDeactivated(WindowEvent e) {}
        });
        
        dokter.addWindowListener(new WindowListener() {
            @Override
            public void windowOpened(WindowEvent e) {}
            @Override
            public void windowClosing(WindowEvent e) {}
            @Override
            public void windowClosed(WindowEvent e) {
                if(dokter.getTable().getSelectedRow()!= -1){ 
                    KdDPJP.setText(dokter.getTable().getValueAt(dokter.getTable().getSelectedRow(),0).toString());
                    NmDPJP.setText(dokter.getTable().getValueAt(dokter.getTable().getSelectedRow(),1).toString());  
                }              
            }
            @Override
            public void windowIconified(WindowEvent e) {}
            @Override
            public void windowDeiconified(WindowEvent e) {}
            @Override
            public void windowActivated(WindowEvent e) {}
            @Override
            public void windowDeactivated(WindowEvent e) {}
        });
    }
    private Dimension screen=Toolkit.getDefaultToolkit().getScreenSize();

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        WindowDPJPranap = new javax.swing.JDialog();
        internalFrame15 = new widget.InternalFrame();
        KdDPJP = new widget.TextBox();
        NmDPJP = new widget.TextBox();
        btnDPJP = new widget.Button();
        KdPetugas = new widget.TextBox();
        NmPetugas = new widget.TextBox();
        KdPetugas2 = new widget.TextBox();
        NmPetugas2 = new widget.TextBox();
        internalFrame1 = new widget.InternalFrame();
        internalFrame4 = new widget.InternalFrame();
        jLabel3 = new widget.Label();
        TNoRW = new widget.TextBox();
        TNoRM = new widget.TextBox();
        TNmPasien = new widget.TextBox();
        jLabel13 = new widget.Label();
        jLabel4 = new widget.Label();
        TtglMasuk = new widget.TextBox();
        TabRekamMedis = new javax.swing.JTabbedPane();
        scrollInput = new widget.ScrollPane();
        FormInput = new widget.PanelBiasa();
        BtnAwalMedisInap = new widget.ButtonBig();
        BtnMedisKandungan = new widget.ButtonBig();
        BtnMedisNeonatus = new widget.ButtonBig();
        BtnAwalKepRanap = new widget.ButtonBig();
        BtnAwalKebidRanap = new widget.ButtonBig();
        BtnAwalKepAnak = new widget.ButtonBig();
        BtnAwalKepNeonatus = new widget.ButtonBig();
        BtnTransferRuang = new widget.ButtonBig();
        BtnMonitoringEWSDewasa = new widget.ButtonBig();
        BtnMonitoringEWSAnak = new widget.ButtonBig();
        BtnMonitoringEWSNeonatus = new widget.ButtonBig();
        BtnMonitoringEWSObstetri = new widget.ButtonBig();
        BtnRisikoJatuh = new widget.ButtonBig();
        BtnRisikoJatuhAnak = new widget.ButtonBig();
        BtnRisikoJatuhGeriatri = new widget.ButtonBig();
        BtnCatatanPersalinan = new widget.ButtonBig();
        BtnResumeInap = new widget.ButtonBig();
        BtnRencanaPemulangan = new widget.ButtonBig();
        scrollInput1 = new widget.ScrollPane();
        FormInput1 = new widget.PanelBiasa();
        BtnPreOperasi = new widget.ButtonBig();
        BtnSignInSbelummAnes = new widget.ButtonBig();
        BtnTimeOutSblumInsisi = new widget.ButtonBig();
        BtnSOMenutupLuka = new widget.ButtonBig();
        BtnChcklisPostOP = new widget.ButtonBig();
        scrollInput2 = new widget.ScrollPane();
        FormInput2 = new widget.PanelBiasa();
        BtnAwalKep = new widget.ButtonBig();
        BtnKeluarHCU = new widget.ButtonBig();
        BtnMasukHCU = new widget.ButtonBig();
        BtnKeluarICU = new widget.ButtonBig();
        BtnMasukICU = new widget.ButtonBig();
        BtnVentilator = new widget.ButtonBig();
        BtnGDS = new widget.ButtonBig();
        BtnReakasiTranfusi = new widget.ButtonBig();
        panelisi1 = new widget.panelisi();
        label9 = new widget.Label();
        BtnRefres = new widget.Button();
        BtnKeluar = new widget.Button();

        WindowDPJPranap.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        WindowDPJPranap.setName("WindowDPJPranap"); // NOI18N
        WindowDPJPranap.setUndecorated(true);
        WindowDPJPranap.setResizable(false);

        internalFrame15.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255), 3), "::[ DPJP Rawat Inap ]::", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        internalFrame15.setName("internalFrame15"); // NOI18N
        internalFrame15.setWarnaBawah(new java.awt.Color(245, 250, 240));
        internalFrame15.setLayout(null);

        KdDPJP.setEditable(false);
        KdDPJP.setForeground(new java.awt.Color(0, 0, 0));
        KdDPJP.setName("KdDPJP"); // NOI18N
        internalFrame15.add(KdDPJP);
        KdDPJP.setBounds(81, 32, 100, 23);

        NmDPJP.setEditable(false);
        NmDPJP.setForeground(new java.awt.Color(0, 0, 0));
        NmDPJP.setName("NmDPJP"); // NOI18N
        internalFrame15.add(NmDPJP);
        NmDPJP.setBounds(183, 32, 380, 23);

        btnDPJP.setForeground(new java.awt.Color(0, 0, 0));
        btnDPJP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/190.png"))); // NOI18N
        btnDPJP.setMnemonic('7');
        btnDPJP.setToolTipText("ALt+7");
        btnDPJP.setName("btnDPJP"); // NOI18N
        btnDPJP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDPJPActionPerformed(evt);
            }
        });
        internalFrame15.add(btnDPJP);
        btnDPJP.setBounds(565, 32, 28, 23);

        KdPetugas.setEditable(false);
        KdPetugas.setForeground(new java.awt.Color(0, 0, 0));
        KdPetugas.setName("KdPetugas"); // NOI18N
        internalFrame15.add(KdPetugas);
        KdPetugas.setBounds(81, 32, 100, 23);

        NmPetugas.setEditable(false);
        NmPetugas.setForeground(new java.awt.Color(0, 0, 0));
        NmPetugas.setName("NmPetugas"); // NOI18N
        internalFrame15.add(NmPetugas);
        NmPetugas.setBounds(81, 32, 100, 23);

        KdPetugas2.setEditable(false);
        KdPetugas2.setForeground(new java.awt.Color(0, 0, 0));
        KdPetugas2.setName("KdPetugas2"); // NOI18N
        internalFrame15.add(KdPetugas2);
        KdPetugas2.setBounds(81, 32, 100, 23);

        NmPetugas2.setEditable(false);
        NmPetugas2.setForeground(new java.awt.Color(0, 0, 0));
        NmPetugas2.setName("NmPetugas2"); // NOI18N
        internalFrame15.add(NmPetugas2);
        NmPetugas2.setBounds(81, 32, 100, 23);

        WindowDPJPranap.getContentPane().add(internalFrame15, java.awt.BorderLayout.CENTER);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        internalFrame1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 245, 235)), "::[ ERM INAP ]::", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(50, 50, 50))); // NOI18N
        internalFrame1.setName("internalFrame1"); // NOI18N
        internalFrame1.setLayout(new java.awt.BorderLayout(1, 1));

        internalFrame4.setName("internalFrame4"); // NOI18N
        internalFrame4.setPreferredSize(new java.awt.Dimension(12, 100));
        internalFrame4.setLayout(null);

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("NoRawat/RM :");
        jLabel3.setName("jLabel3"); // NOI18N
        internalFrame4.add(jLabel3);
        jLabel3.setBounds(0, 10, 103, 23);

        TNoRW.setEditable(false);
        TNoRW.setForeground(new java.awt.Color(0, 0, 0));
        TNoRW.setName("TNoRW"); // NOI18N
        internalFrame4.add(TNoRW);
        TNoRW.setBounds(107, 10, 122, 23);

        TNoRM.setEditable(false);
        TNoRM.setForeground(new java.awt.Color(0, 0, 0));
        TNoRM.setName("TNoRM"); // NOI18N
        internalFrame4.add(TNoRM);
        TNoRM.setBounds(230, 10, 70, 23);

        TNmPasien.setEditable(false);
        TNmPasien.setForeground(new java.awt.Color(0, 0, 0));
        TNmPasien.setName("TNmPasien"); // NOI18N
        internalFrame4.add(TNmPasien);
        TNmPasien.setBounds(110, 40, 280, 23);

        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Nama :");
        jLabel13.setName("jLabel13"); // NOI18N
        internalFrame4.add(jLabel13);
        jLabel13.setBounds(0, 38, 103, 23);

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Tgl. Masuk :");
        jLabel4.setName("jLabel4"); // NOI18N
        internalFrame4.add(jLabel4);
        jLabel4.setBounds(0, 66, 103, 23);

        TtglMasuk.setEditable(false);
        TtglMasuk.setForeground(new java.awt.Color(0, 0, 0));
        TtglMasuk.setName("TtglMasuk"); // NOI18N
        internalFrame4.add(TtglMasuk);
        TtglMasuk.setBounds(107, 66, 210, 23);

        internalFrame1.add(internalFrame4, java.awt.BorderLayout.PAGE_START);

        TabRekamMedis.setBackground(new java.awt.Color(255, 255, 254));
        TabRekamMedis.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        TabRekamMedis.setName("TabRekamMedis"); // NOI18N
        TabRekamMedis.setPreferredSize(new java.awt.Dimension(270, 106));

        scrollInput.setName("scrollInput"); // NOI18N
        scrollInput.setPreferredSize(new java.awt.Dimension(102, 557));

        FormInput.setBackground(new java.awt.Color(255, 255, 255));
        FormInput.setBorder(null);
        FormInput.setName("FormInput"); // NOI18N
        FormInput.setPreferredSize(new java.awt.Dimension(870, 834));
        FormInput.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 8, 25));

        BtnAwalMedisInap.setForeground(new java.awt.Color(0, 0, 0));
        BtnAwalMedisInap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/doctor2.png"))); // NOI18N
        BtnAwalMedisInap.setText("Asesmen Awal Medis");
        BtnAwalMedisInap.setIconTextGap(0);
        BtnAwalMedisInap.setName("BtnAwalMedisInap"); // NOI18N
        BtnAwalMedisInap.setPreferredSize(new java.awt.Dimension(200, 90));
        BtnAwalMedisInap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAwalMedisInapActionPerformed(evt);
            }
        });
        FormInput.add(BtnAwalMedisInap);

        BtnMedisKandungan.setForeground(new java.awt.Color(0, 0, 0));
        BtnMedisKandungan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/doctor2.png"))); // NOI18N
        BtnMedisKandungan.setText("Asesmen Awal Medis Kandungan");
        BtnMedisKandungan.setIconTextGap(0);
        BtnMedisKandungan.setName("BtnMedisKandungan"); // NOI18N
        BtnMedisKandungan.setPreferredSize(new java.awt.Dimension(200, 90));
        BtnMedisKandungan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMedisKandunganActionPerformed(evt);
            }
        });
        FormInput.add(BtnMedisKandungan);

        BtnMedisNeonatus.setForeground(new java.awt.Color(0, 0, 0));
        BtnMedisNeonatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/doctor2.png"))); // NOI18N
        BtnMedisNeonatus.setText("Asesmen Awal Medis Neonatus");
        BtnMedisNeonatus.setIconTextGap(0);
        BtnMedisNeonatus.setName("BtnMedisNeonatus"); // NOI18N
        BtnMedisNeonatus.setPreferredSize(new java.awt.Dimension(200, 90));
        BtnMedisNeonatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMedisNeonatusActionPerformed(evt);
            }
        });
        FormInput.add(BtnMedisNeonatus);

        BtnAwalKepRanap.setForeground(new java.awt.Color(0, 0, 0));
        BtnAwalKepRanap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/2620509_employee_job_note_seeker_unemployee_icon.png"))); // NOI18N
        BtnAwalKepRanap.setText("Awal Keprawatan Dewasa");
        BtnAwalKepRanap.setIconTextGap(0);
        BtnAwalKepRanap.setName("BtnAwalKepRanap"); // NOI18N
        BtnAwalKepRanap.setPreferredSize(new java.awt.Dimension(200, 90));
        BtnAwalKepRanap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAwalKepRanapActionPerformed(evt);
            }
        });
        FormInput.add(BtnAwalKepRanap);

        BtnAwalKebidRanap.setForeground(new java.awt.Color(0, 0, 0));
        BtnAwalKebidRanap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/2620509_employee_job_note_seeker_unemployee_icon.png"))); // NOI18N
        BtnAwalKebidRanap.setText("Awal Kebidanan");
        BtnAwalKebidRanap.setIconTextGap(0);
        BtnAwalKebidRanap.setName("BtnAwalKebidRanap"); // NOI18N
        BtnAwalKebidRanap.setPreferredSize(new java.awt.Dimension(200, 90));
        BtnAwalKebidRanap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAwalKebidRanapActionPerformed(evt);
            }
        });
        FormInput.add(BtnAwalKebidRanap);

        BtnAwalKepAnak.setForeground(new java.awt.Color(0, 0, 0));
        BtnAwalKepAnak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/2620509_employee_job_note_seeker_unemployee_icon.png"))); // NOI18N
        BtnAwalKepAnak.setText("Awal Keprawatan Anak");
        BtnAwalKepAnak.setIconTextGap(0);
        BtnAwalKepAnak.setName("BtnAwalKepAnak"); // NOI18N
        BtnAwalKepAnak.setPreferredSize(new java.awt.Dimension(200, 90));
        BtnAwalKepAnak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAwalKepAnakActionPerformed(evt);
            }
        });
        FormInput.add(BtnAwalKepAnak);

        BtnAwalKepNeonatus.setForeground(new java.awt.Color(0, 0, 0));
        BtnAwalKepNeonatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/2620509_employee_job_note_seeker_unemployee_icon.png"))); // NOI18N
        BtnAwalKepNeonatus.setText("Awal Keprawatan Neonatus");
        BtnAwalKepNeonatus.setIconTextGap(0);
        BtnAwalKepNeonatus.setName("BtnAwalKepNeonatus"); // NOI18N
        BtnAwalKepNeonatus.setPreferredSize(new java.awt.Dimension(200, 90));
        BtnAwalKepNeonatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAwalKepNeonatusActionPerformed(evt);
            }
        });
        FormInput.add(BtnAwalKepNeonatus);

        BtnTransferRuang.setForeground(new java.awt.Color(0, 0, 0));
        BtnTransferRuang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/1481002123_wheelchair.png"))); // NOI18N
        BtnTransferRuang.setText("Lembar Transfer Ruang");
        BtnTransferRuang.setIconTextGap(0);
        BtnTransferRuang.setName("BtnTransferRuang"); // NOI18N
        BtnTransferRuang.setPreferredSize(new java.awt.Dimension(200, 90));
        BtnTransferRuang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTransferRuangActionPerformed(evt);
            }
        });
        FormInput.add(BtnTransferRuang);

        BtnMonitoringEWSDewasa.setForeground(new java.awt.Color(0, 0, 0));
        BtnMonitoringEWSDewasa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/if_gtk-find-and-replace_39047.png"))); // NOI18N
        BtnMonitoringEWSDewasa.setText("Monitoring EWS Dewasa");
        BtnMonitoringEWSDewasa.setIconTextGap(0);
        BtnMonitoringEWSDewasa.setName("BtnMonitoringEWSDewasa"); // NOI18N
        BtnMonitoringEWSDewasa.setPreferredSize(new java.awt.Dimension(200, 90));
        BtnMonitoringEWSDewasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMonitoringEWSDewasaActionPerformed(evt);
            }
        });
        FormInput.add(BtnMonitoringEWSDewasa);

        BtnMonitoringEWSAnak.setForeground(new java.awt.Color(0, 0, 0));
        BtnMonitoringEWSAnak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/if_gtk-find-and-replace_39047.png"))); // NOI18N
        BtnMonitoringEWSAnak.setText("Monitoring EWS Anak");
        BtnMonitoringEWSAnak.setIconTextGap(0);
        BtnMonitoringEWSAnak.setName("BtnMonitoringEWSAnak"); // NOI18N
        BtnMonitoringEWSAnak.setPreferredSize(new java.awt.Dimension(200, 90));
        BtnMonitoringEWSAnak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMonitoringEWSAnakActionPerformed(evt);
            }
        });
        FormInput.add(BtnMonitoringEWSAnak);

        BtnMonitoringEWSNeonatus.setForeground(new java.awt.Color(0, 0, 0));
        BtnMonitoringEWSNeonatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/if_gtk-find-and-replace_39047.png"))); // NOI18N
        BtnMonitoringEWSNeonatus.setText("Monitoring EWS Neonatus");
        BtnMonitoringEWSNeonatus.setIconTextGap(0);
        BtnMonitoringEWSNeonatus.setName("BtnMonitoringEWSNeonatus"); // NOI18N
        BtnMonitoringEWSNeonatus.setPreferredSize(new java.awt.Dimension(200, 90));
        BtnMonitoringEWSNeonatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMonitoringEWSNeonatusActionPerformed(evt);
            }
        });
        FormInput.add(BtnMonitoringEWSNeonatus);

        BtnMonitoringEWSObstetri.setForeground(new java.awt.Color(0, 0, 0));
        BtnMonitoringEWSObstetri.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/if_gtk-find-and-replace_39047.png"))); // NOI18N
        BtnMonitoringEWSObstetri.setText("Monitoring EWS Obstetri");
        BtnMonitoringEWSObstetri.setIconTextGap(0);
        BtnMonitoringEWSObstetri.setName("BtnMonitoringEWSObstetri"); // NOI18N
        BtnMonitoringEWSObstetri.setPreferredSize(new java.awt.Dimension(200, 90));
        BtnMonitoringEWSObstetri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMonitoringEWSObstetriActionPerformed(evt);
            }
        });
        FormInput.add(BtnMonitoringEWSObstetri);

        BtnRisikoJatuh.setForeground(new java.awt.Color(0, 0, 0));
        BtnRisikoJatuh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/iconfinder_software-update-urgent_118956.png"))); // NOI18N
        BtnRisikoJatuh.setText("Risiko Jatuh Dewasa");
        BtnRisikoJatuh.setIconTextGap(0);
        BtnRisikoJatuh.setName("BtnRisikoJatuh"); // NOI18N
        BtnRisikoJatuh.setPreferredSize(new java.awt.Dimension(200, 90));
        BtnRisikoJatuh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRisikoJatuhActionPerformed(evt);
            }
        });
        FormInput.add(BtnRisikoJatuh);

        BtnRisikoJatuhAnak.setForeground(new java.awt.Color(0, 0, 0));
        BtnRisikoJatuhAnak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/iconfinder_software-update-urgent_118956.png"))); // NOI18N
        BtnRisikoJatuhAnak.setText("Risiko Jatuh Anak");
        BtnRisikoJatuhAnak.setIconTextGap(0);
        BtnRisikoJatuhAnak.setName("BtnRisikoJatuhAnak"); // NOI18N
        BtnRisikoJatuhAnak.setPreferredSize(new java.awt.Dimension(200, 90));
        BtnRisikoJatuhAnak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRisikoJatuhAnakActionPerformed(evt);
            }
        });
        FormInput.add(BtnRisikoJatuhAnak);

        BtnRisikoJatuhGeriatri.setForeground(new java.awt.Color(0, 0, 0));
        BtnRisikoJatuhGeriatri.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/iconfinder_software-update-urgent_118956.png"))); // NOI18N
        BtnRisikoJatuhGeriatri.setText("Risiko Jatuh Geriatri");
        BtnRisikoJatuhGeriatri.setIconTextGap(0);
        BtnRisikoJatuhGeriatri.setName("BtnRisikoJatuhGeriatri"); // NOI18N
        BtnRisikoJatuhGeriatri.setPreferredSize(new java.awt.Dimension(200, 90));
        BtnRisikoJatuhGeriatri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRisikoJatuhGeriatriActionPerformed(evt);
            }
        });
        FormInput.add(BtnRisikoJatuhGeriatri);

        BtnCatatanPersalinan.setForeground(new java.awt.Color(0, 0, 0));
        BtnCatatanPersalinan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/6771569_education_learning_pencil_school_signature_icon.png"))); // NOI18N
        BtnCatatanPersalinan.setText("Catatan Persalinan");
        BtnCatatanPersalinan.setIconTextGap(0);
        BtnCatatanPersalinan.setName("BtnCatatanPersalinan"); // NOI18N
        BtnCatatanPersalinan.setPreferredSize(new java.awt.Dimension(200, 90));
        BtnCatatanPersalinan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCatatanPersalinanActionPerformed(evt);
            }
        });
        FormInput.add(BtnCatatanPersalinan);

        BtnResumeInap.setForeground(new java.awt.Color(0, 0, 0));
        BtnResumeInap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/1360485642_edit-notes.png"))); // NOI18N
        BtnResumeInap.setText("Ringkasan Pulang / Resume");
        BtnResumeInap.setIconTextGap(0);
        BtnResumeInap.setName("BtnResumeInap"); // NOI18N
        BtnResumeInap.setPreferredSize(new java.awt.Dimension(200, 90));
        BtnResumeInap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnResumeInapActionPerformed(evt);
            }
        });
        FormInput.add(BtnResumeInap);

        BtnRencanaPemulangan.setForeground(new java.awt.Color(0, 0, 0));
        BtnRencanaPemulangan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/1360485642_edit-notes.png"))); // NOI18N
        BtnRencanaPemulangan.setText("Rencana Pemulangan");
        BtnRencanaPemulangan.setIconTextGap(0);
        BtnRencanaPemulangan.setName("BtnRencanaPemulangan"); // NOI18N
        BtnRencanaPemulangan.setPreferredSize(new java.awt.Dimension(200, 90));
        BtnRencanaPemulangan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRencanaPemulanganActionPerformed(evt);
            }
        });
        FormInput.add(BtnRencanaPemulangan);

        scrollInput.setViewportView(FormInput);

        TabRekamMedis.addTab("Ruang Rawat Inap", scrollInput);

        scrollInput1.setName("scrollInput1"); // NOI18N
        scrollInput1.setPreferredSize(new java.awt.Dimension(102, 557));

        FormInput1.setBackground(new java.awt.Color(255, 255, 255));
        FormInput1.setBorder(null);
        FormInput1.setName("FormInput1"); // NOI18N
        FormInput1.setPreferredSize(new java.awt.Dimension(870, 834));
        FormInput1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 8, 25));

        BtnPreOperasi.setForeground(new java.awt.Color(0, 0, 0));
        BtnPreOperasi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/1360816018_tests.png"))); // NOI18N
        BtnPreOperasi.setText("RM Penilaian Pre Operasi");
        BtnPreOperasi.setIconTextGap(0);
        BtnPreOperasi.setName("BtnPreOperasi"); // NOI18N
        BtnPreOperasi.setPreferredSize(new java.awt.Dimension(200, 90));
        BtnPreOperasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPreOperasiActionPerformed(evt);
            }
        });
        FormInput1.add(BtnPreOperasi);

        BtnSignInSbelummAnes.setForeground(new java.awt.Color(0, 0, 0));
        BtnSignInSbelummAnes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/1360816018_tests.png"))); // NOI18N
        BtnSignInSbelummAnes.setText("Sign In Sebelum Anastesi");
        BtnSignInSbelummAnes.setIconTextGap(0);
        BtnSignInSbelummAnes.setName("BtnSignInSbelummAnes"); // NOI18N
        BtnSignInSbelummAnes.setPreferredSize(new java.awt.Dimension(200, 90));
        BtnSignInSbelummAnes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSignInSbelummAnesActionPerformed(evt);
            }
        });
        FormInput1.add(BtnSignInSbelummAnes);

        BtnTimeOutSblumInsisi.setForeground(new java.awt.Color(0, 0, 0));
        BtnTimeOutSblumInsisi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/1360816018_tests.png"))); // NOI18N
        BtnTimeOutSblumInsisi.setText("Time Out Sebelum Insisi");
        BtnTimeOutSblumInsisi.setIconTextGap(0);
        BtnTimeOutSblumInsisi.setName("BtnTimeOutSblumInsisi"); // NOI18N
        BtnTimeOutSblumInsisi.setPreferredSize(new java.awt.Dimension(200, 90));
        BtnTimeOutSblumInsisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTimeOutSblumInsisiActionPerformed(evt);
            }
        });
        FormInput1.add(BtnTimeOutSblumInsisi);

        BtnSOMenutupLuka.setForeground(new java.awt.Color(0, 0, 0));
        BtnSOMenutupLuka.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/1360816018_tests.png"))); // NOI18N
        BtnSOMenutupLuka.setText("Sign Out Sebelum Menutup Luka");
        BtnSOMenutupLuka.setIconTextGap(0);
        BtnSOMenutupLuka.setName("BtnSOMenutupLuka"); // NOI18N
        BtnSOMenutupLuka.setPreferredSize(new java.awt.Dimension(200, 90));
        BtnSOMenutupLuka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSOMenutupLukaActionPerformed(evt);
            }
        });
        FormInput1.add(BtnSOMenutupLuka);

        BtnChcklisPostOP.setForeground(new java.awt.Color(0, 0, 0));
        BtnChcklisPostOP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/1360816018_tests.png"))); // NOI18N
        BtnChcklisPostOP.setText("Checklist Post OP");
        BtnChcklisPostOP.setIconTextGap(0);
        BtnChcklisPostOP.setName("BtnChcklisPostOP"); // NOI18N
        BtnChcklisPostOP.setPreferredSize(new java.awt.Dimension(200, 90));
        BtnChcklisPostOP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnChcklisPostOPActionPerformed(evt);
            }
        });
        FormInput1.add(BtnChcklisPostOP);

        scrollInput1.setViewportView(FormInput1);

        TabRekamMedis.addTab("Instalasi Bedah Sentral (IBS)", scrollInput1);

        scrollInput2.setName("scrollInput2"); // NOI18N
        scrollInput2.setPreferredSize(new java.awt.Dimension(102, 557));

        FormInput2.setBackground(new java.awt.Color(255, 255, 255));
        FormInput2.setBorder(null);
        FormInput2.setName("FormInput2"); // NOI18N
        FormInput2.setPreferredSize(new java.awt.Dimension(870, 834));
        FormInput2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 8, 25));

        BtnAwalKep.setForeground(new java.awt.Color(0, 0, 0));
        BtnAwalKep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/2620509_employee_job_note_seeker_unemployee_icon.png"))); // NOI18N
        BtnAwalKep.setText(" Awal Keperawatan");
        BtnAwalKep.setIconTextGap(0);
        BtnAwalKep.setName("BtnAwalKep"); // NOI18N
        BtnAwalKep.setPreferredSize(new java.awt.Dimension(200, 90));
        BtnAwalKep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAwalKepActionPerformed(evt);
            }
        });
        FormInput2.add(BtnAwalKep);

        BtnKeluarHCU.setForeground(new java.awt.Color(0, 0, 0));
        BtnKeluarHCU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/2620509_employee_job_note_seeker_unemployee_icon.png"))); // NOI18N
        BtnKeluarHCU.setText("Kreteria Keluar HCU");
        BtnKeluarHCU.setIconTextGap(0);
        BtnKeluarHCU.setName("BtnKeluarHCU"); // NOI18N
        BtnKeluarHCU.setPreferredSize(new java.awt.Dimension(200, 90));
        BtnKeluarHCU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKeluarHCUActionPerformed(evt);
            }
        });
        FormInput2.add(BtnKeluarHCU);

        BtnMasukHCU.setForeground(new java.awt.Color(0, 0, 0));
        BtnMasukHCU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/2620509_employee_job_note_seeker_unemployee_icon.png"))); // NOI18N
        BtnMasukHCU.setText("Kreteria Masuk HCU");
        BtnMasukHCU.setIconTextGap(0);
        BtnMasukHCU.setName("BtnMasukHCU"); // NOI18N
        BtnMasukHCU.setPreferredSize(new java.awt.Dimension(200, 90));
        BtnMasukHCU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMasukHCUActionPerformed(evt);
            }
        });
        FormInput2.add(BtnMasukHCU);

        BtnKeluarICU.setForeground(new java.awt.Color(0, 0, 0));
        BtnKeluarICU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/2620509_employee_job_note_seeker_unemployee_icon.png"))); // NOI18N
        BtnKeluarICU.setText("Kreteria Keluar ICU");
        BtnKeluarICU.setIconTextGap(0);
        BtnKeluarICU.setName("BtnKeluarICU"); // NOI18N
        BtnKeluarICU.setPreferredSize(new java.awt.Dimension(200, 90));
        BtnKeluarICU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKeluarICUActionPerformed(evt);
            }
        });
        FormInput2.add(BtnKeluarICU);

        BtnMasukICU.setForeground(new java.awt.Color(0, 0, 0));
        BtnMasukICU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/2620509_employee_job_note_seeker_unemployee_icon.png"))); // NOI18N
        BtnMasukICU.setText("Kreteria Masuk ICU");
        BtnMasukICU.setIconTextGap(0);
        BtnMasukICU.setName("BtnMasukICU"); // NOI18N
        BtnMasukICU.setPreferredSize(new java.awt.Dimension(200, 90));
        BtnMasukICU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMasukICUActionPerformed(evt);
            }
        });
        FormInput2.add(BtnMasukICU);

        BtnVentilator.setForeground(new java.awt.Color(0, 0, 0));
        BtnVentilator.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/6088631_bed_hospital_icu_medical_treatment_icon.png"))); // NOI18N
        BtnVentilator.setText("Observasi Ventilator");
        BtnVentilator.setIconTextGap(0);
        BtnVentilator.setName("BtnVentilator"); // NOI18N
        BtnVentilator.setPreferredSize(new java.awt.Dimension(200, 90));
        BtnVentilator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVentilatorActionPerformed(evt);
            }
        });
        FormInput2.add(BtnVentilator);

        BtnGDS.setForeground(new java.awt.Color(0, 0, 0));
        BtnGDS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/6427847_information_note_notebook_sheet_icon.png"))); // NOI18N
        BtnGDS.setText("Cek GDS");
        BtnGDS.setIconTextGap(0);
        BtnGDS.setName("BtnGDS"); // NOI18N
        BtnGDS.setPreferredSize(new java.awt.Dimension(200, 90));
        BtnGDS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGDSActionPerformed(evt);
            }
        });
        FormInput2.add(BtnGDS);

        BtnReakasiTranfusi.setForeground(new java.awt.Color(0, 0, 0));
        BtnReakasiTranfusi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/6088722_blood_bottle_packet_icon.png"))); // NOI18N
        BtnReakasiTranfusi.setText("Monitoring Reaksi Tranfusi");
        BtnReakasiTranfusi.setIconTextGap(0);
        BtnReakasiTranfusi.setName("BtnReakasiTranfusi"); // NOI18N
        BtnReakasiTranfusi.setPreferredSize(new java.awt.Dimension(200, 90));
        BtnReakasiTranfusi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnReakasiTranfusiActionPerformed(evt);
            }
        });
        FormInput2.add(BtnReakasiTranfusi);

        scrollInput2.setViewportView(FormInput2);

        TabRekamMedis.addTab("Intensive Care Unit (ICU)", scrollInput2);

        internalFrame1.add(TabRekamMedis, java.awt.BorderLayout.CENTER);

        panelisi1.setName("panelisi1"); // NOI18N
        panelisi1.setPreferredSize(new java.awt.Dimension(100, 56));
        panelisi1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 9));

        label9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label9.setName("label9"); // NOI18N
        label9.setPreferredSize(new java.awt.Dimension(20, 30));
        panelisi1.add(label9);

        BtnRefres.setForeground(new java.awt.Color(0, 0, 0));
        BtnRefres.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/42a.png"))); // NOI18N
        BtnRefres.setMnemonic('R');
        BtnRefres.setText("Refresh Rekam Medis");
        BtnRefres.setToolTipText("Alt+R");
        BtnRefres.setName("BtnRefres"); // NOI18N
        BtnRefres.setPreferredSize(new java.awt.Dimension(186, 30));
        BtnRefres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRefresActionPerformed(evt);
            }
        });
        panelisi1.add(BtnRefres);

        BtnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/exit.png"))); // NOI18N
        BtnKeluar.setMnemonic('K');
        BtnKeluar.setText("Keluar");
        BtnKeluar.setToolTipText("Alt+K");
        BtnKeluar.setName("BtnKeluar"); // NOI18N
        BtnKeluar.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKeluarActionPerformed(evt);
            }
        });
        BtnKeluar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnKeluarKeyPressed(evt);
            }
        });
        panelisi1.add(BtnKeluar);

        internalFrame1.add(panelisi1, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(internalFrame1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
/*
private void KdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TKdKeyPressed
    Valid.pindah(evt,BtnCari,Nm);
}//GEN-LAST:event_TKdKeyPressed
*/

    private void BtnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKeluarActionPerformed
        dispose();
    }//GEN-LAST:event_BtnKeluarActionPerformed

    private void BtnKeluarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnKeluarKeyPressed
        TNoRW.setText("");
        TNoRM.setText("");
        TNmPasien.setText("");
        stts = "";
        kdkamar = "";        
        gedung = "";
        TtglMasuk.setText("");
        dispose();
    }//GEN-LAST:event_BtnKeluarKeyPressed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        isCek();
    }//GEN-LAST:event_formWindowOpened

    private void BtnRefresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRefresActionPerformed
        tombolCek(TNoRW.getText());
    }//GEN-LAST:event_BtnRefresActionPerformed

    private void BtnPreOperasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPreOperasiActionPerformed
        if (TNoRW.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, Silahkan anda pilih dulu salah satu datanya pada tabel...!!!");
        } else {
            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            akses.setform("DlgERM");
            RMPenilaianPreOperasi form = new RMPenilaianPreOperasi(null, false);
            form.emptTeks();
            form.isCek();
            form.setPasien(TNoRW.getText());
            form.setSize(internalFrame1.getWidth(), internalFrame1.getHeight());
            form.setLocationRelativeTo(internalFrame1);
            form.setVisible(true);
            this.setCursor(Cursor.getDefaultCursor());
        }
    }//GEN-LAST:event_BtnPreOperasiActionPerformed

    private void BtnResumeInapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnResumeInapActionPerformed
        if (TNoRW.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, Silahkan anda pilih dulu salah satu datanya pada tabel...!!!");
        } else {
            if (Sequel.cariInteger("select count(-1) from dpjp_ranap where no_rawat='" + TNoRW.getText() + "'") == 0) {
                x = JOptionPane.showConfirmDialog(rootPane, "DPJP pasien ini belum ditentukan, apakah DPJP nya akan dipilih dulu..??", "Konfirmasi", JOptionPane.YES_NO_OPTION);
                if (x == JOptionPane.YES_OPTION) {
                    WindowDPJPranap.setSize(615, 110);
                    WindowDPJPranap.setLocationRelativeTo(internalFrame1);
                    WindowDPJPranap.setVisible(true);
                    KdDPJP.setText(Sequel.cariIsi("select ifnull(kd_dokter,'') from dpjp_ranap where no_rawat='" + TNoRW.getText() + "'"));
                    if (KdDPJP.getText().equals("")) {
                        NmDPJP.setText("");
                    } else {
                        NmDPJP.setText(Sequel.cariIsi("select nm_dokter from dokter where kd_dokter='" + KdDPJP.getText() + "'"));
                    }
                    btnDPJP.requestFocus();
                } else {
                    BtnKeluarActionPerformed(null);
                }
            } else {
                akses.setform("DlgERM");
                RMDataResumePasienRanap ringkasan = new RMDataResumePasienRanap(null, false);
                ringkasan.emptTeks();
                ringkasan.isCek();
                ringkasan.setPasien(TNoRW.getText());
                ringkasan.setSize(internalFrame1.getWidth(), internalFrame1.getHeight());
                ringkasan.setLocationRelativeTo(internalFrame1);
                ringkasan.setVisible(true);
            }
        }
    }//GEN-LAST:event_BtnResumeInapActionPerformed

    private void btnDPJPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDPJPActionPerformed
        akses.setform("DlgERM");
        dokter.emptTeks();
        dokter.isCek();
        dokter.setSize(internalFrame1.getWidth(), internalFrame1.getHeight());
        dokter.setLocationRelativeTo(internalFrame1);
        dokter.setVisible(true);
    }//GEN-LAST:event_btnDPJPActionPerformed

    private void BtnAwalMedisInapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAwalMedisInapActionPerformed
        if (TNoRW.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, Silahkan anda pilih dulu salah satu datanya pada tabel...!!!");
        } else {
            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            akses.setform("DlgERM");
            RMPenilaianAwalMedisRanapDewasa form = new RMPenilaianAwalMedisRanapDewasa(null, false);
            form.emptTeks();
            form.isCek();
            form.setNoRm2(TNoRW.getText());
            form.setSize(internalFrame1.getWidth(), internalFrame1.getHeight());
            form.setLocationRelativeTo(internalFrame1);
            form.setVisible(true);
            this.setCursor(Cursor.getDefaultCursor());
        }// TODO add your handling code here:
    }//GEN-LAST:event_BtnAwalMedisInapActionPerformed

    private void BtnMedisKandunganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMedisKandunganActionPerformed
        if (TNoRW.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, Silahkan anda pilih dulu salah satu datanya pada tabel...!!!");
        } else {
            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            akses.setform("DlgERM");
            RMPenilaianAwalMedisRanapKandungan form = new RMPenilaianAwalMedisRanapKandungan(null, false);
            form.emptTeks();
            form.isCek();
            form.setNoRm2(TNoRW.getText());
            form.setSize(internalFrame1.getWidth(), internalFrame1.getHeight());
            form.setLocationRelativeTo(internalFrame1);
            form.setVisible(true);
            this.setCursor(Cursor.getDefaultCursor());
        }// TODO add your handling code here:
    }//GEN-LAST:event_BtnMedisKandunganActionPerformed

    private void BtnTransferRuangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTransferRuangActionPerformed
        if (TNoRW.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, Silahkan anda pilih dulu salah satu datanya pada tabel...!!!");
        } else {
            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            akses.setform("DlgERM");
            RMTransferPasienAntarRuang form = new RMTransferPasienAntarRuang(null, false);
            form.emptTeks();
            form.isCek();
            form.setNoRm2(TNoRW.getText());
            form.setSize(internalFrame1.getWidth(), internalFrame1.getHeight());
            form.setLocationRelativeTo(internalFrame1);
            form.setVisible(true);
            this.setCursor(Cursor.getDefaultCursor());
        }// TODO add your handling code here:
    }//GEN-LAST:event_BtnTransferRuangActionPerformed

    private void BtnMedisNeonatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMedisNeonatusActionPerformed
        if (TNoRW.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, Silahkan anda pilih dulu salah satu datanya pada tabel...!!!");
        } else {
            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            akses.setform("DlgERM");
            RMPenilaianAwalMedisRanapNeonatus form = new RMPenilaianAwalMedisRanapNeonatus (null, false);
            form.emptTeks();
            form.isCek();
            form.setNoRm2(TNoRW.getText());
            form.setSize(internalFrame1.getWidth(), internalFrame1.getHeight());
            form.setLocationRelativeTo(internalFrame1);
            form.setVisible(true);
            this.setCursor(Cursor.getDefaultCursor());
        }// TODO add your handling code here:
    }//GEN-LAST:event_BtnMedisNeonatusActionPerformed

    private void BtnAwalKepAnakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAwalKepAnakActionPerformed
        if (TNoRW.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, Silahkan anda pilih dulu salah satu datanya pada tabel...!!!");
        } else {
            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            akses.setform("DlgERM");
            RMPenilaianAwalKeperawatanRanapBayiAnak form = new RMPenilaianAwalKeperawatanRanapBayiAnak (null, false);
            form.emptTeks();
            form.isCek();
            form.setNoRm2(TNoRW.getText());
            form.setSize(internalFrame1.getWidth(), internalFrame1.getHeight());
            form.setLocationRelativeTo(internalFrame1);
            form.setVisible(true);
            this.setCursor(Cursor.getDefaultCursor());
        }// TODO add your handling code here:
    }//GEN-LAST:event_BtnAwalKepAnakActionPerformed

    private void BtnAwalKepNeonatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAwalKepNeonatusActionPerformed
        if (TNoRW.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, Silahkan anda pilih dulu salah satu datanya pada tabel...!!!");
        } else {
            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            akses.setform("DlgERM");
            RMPenilaianAwalKeperawatanRanapNeonatus form = new RMPenilaianAwalKeperawatanRanapNeonatus (null, false);
            form.emptTeks();
            form.isCek();
            form.setNoRm2(TNoRW.getText());
            form.setSize(internalFrame1.getWidth(), internalFrame1.getHeight());
            form.setLocationRelativeTo(internalFrame1);
            form.setVisible(true);
            this.setCursor(Cursor.getDefaultCursor());
        }// TODO add your handling code here:
    }//GEN-LAST:event_BtnAwalKepNeonatusActionPerformed

    private void BtnMonitoringEWSDewasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMonitoringEWSDewasaActionPerformed
        if (TNoRW.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, Silahkan anda pilih dulu salah satu datanya pada tabel...!!!");
        } else {
            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            akses.setform("DlgERM");
            RMPemantauanEWSD form = new RMPemantauanEWSD (null, false);
            form.emptTeks();
            form.isCek();
            form.setNoRm2(TNoRW.getText());
            form.setSize(internalFrame1.getWidth(), internalFrame1.getHeight());
            form.setLocationRelativeTo(internalFrame1);
            form.setVisible(true);
            this.setCursor(Cursor.getDefaultCursor());
        }// TODO add your handling code here:
    }//GEN-LAST:event_BtnMonitoringEWSDewasaActionPerformed

    private void BtnMonitoringEWSAnakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMonitoringEWSAnakActionPerformed
        if (TNoRW.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, Silahkan anda pilih dulu salah satu datanya pada tabel...!!!");
        } else {
            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            akses.setform("DlgERM");
            RMPemantauanPEWS form = new RMPemantauanPEWS (null, false);
            form.emptTeks();
            form.isCek();
            form.setNoRm2(TNoRW.getText());
            form.setSize(internalFrame1.getWidth(), internalFrame1.getHeight());
            form.setLocationRelativeTo(internalFrame1);
            form.setVisible(true);
            this.setCursor(Cursor.getDefaultCursor());
        }// TODO add your handling code here:
    }//GEN-LAST:event_BtnMonitoringEWSAnakActionPerformed

    private void BtnMonitoringEWSNeonatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMonitoringEWSNeonatusActionPerformed
        if (TNoRW.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, Silahkan anda pilih dulu salah satu datanya pada tabel...!!!");
        } else {
            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            akses.setform("DlgERM");
            RMPemantauanEWSNeonatus form = new RMPemantauanEWSNeonatus (null, false);
            form.emptTeks();
            form.isCek();
            form.setNoRm2(TNoRW.getText());
            form.setSize(internalFrame1.getWidth(), internalFrame1.getHeight());
            form.setLocationRelativeTo(internalFrame1);
            form.setVisible(true);
            this.setCursor(Cursor.getDefaultCursor());
        }// TODO add your handling code here:
    }//GEN-LAST:event_BtnMonitoringEWSNeonatusActionPerformed

    private void BtnMonitoringEWSObstetriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMonitoringEWSObstetriActionPerformed
        if (TNoRW.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, Silahkan anda pilih dulu salah satu datanya pada tabel...!!!");
        } else {
            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            akses.setform("DlgERM");
            RMPemantauanMEOWS form = new RMPemantauanMEOWS (null, false);
            form.emptTeks();
            form.isCek();
            form.setNoRm2(TNoRW.getText());
            form.setSize(internalFrame1.getWidth(), internalFrame1.getHeight());
            form.setLocationRelativeTo(internalFrame1);
            form.setVisible(true);
            this.setCursor(Cursor.getDefaultCursor());
        }// TODO add your handling code here:
    }//GEN-LAST:event_BtnMonitoringEWSObstetriActionPerformed

    private void BtnRisikoJatuhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRisikoJatuhActionPerformed
        if (TNoRW.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, Silahkan anda pilih dulu salah satu datanya pada tabel...!!!");
        } else {
            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            akses.setform("DlgERM");
            RMPenilaianLanjutanRisikoJatuhDewasa form = new RMPenilaianLanjutanRisikoJatuhDewasa (null, false);
            form.emptTeks();
            form.isCek();
            form.setNoRm2(TNoRW.getText());
            form.setSize(internalFrame1.getWidth(), internalFrame1.getHeight());
            form.setLocationRelativeTo(internalFrame1);
            form.setVisible(true);
            this.setCursor(Cursor.getDefaultCursor());
        }// TODO add your handling code here:
    }//GEN-LAST:event_BtnRisikoJatuhActionPerformed

    private void BtnRisikoJatuhAnakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRisikoJatuhAnakActionPerformed
        if (TNoRW.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, Silahkan anda pilih dulu salah satu datanya pada tabel...!!!");
        } else {
            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            akses.setform("DlgERM");
            RMPenilaianLanjutanRisikoJatuhAnak form = new RMPenilaianLanjutanRisikoJatuhAnak (null, false);
            form.emptTeks();
            form.isCek();
            form.setNoRm2(TNoRW.getText());
            form.setSize(internalFrame1.getWidth(), internalFrame1.getHeight());
            form.setLocationRelativeTo(internalFrame1);
            form.setVisible(true);
            this.setCursor(Cursor.getDefaultCursor());
        }// TODO add your handling code here:
    }//GEN-LAST:event_BtnRisikoJatuhAnakActionPerformed

    private void BtnRisikoJatuhGeriatriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRisikoJatuhGeriatriActionPerformed
        if (TNoRW.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, Silahkan anda pilih dulu salah satu datanya pada tabel...!!!");
        } else {
            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            akses.setform("DlgERM");
            RMPenilaianLanjutanRisikoJatuhGeriatri form = new RMPenilaianLanjutanRisikoJatuhGeriatri (null, false);
            form.emptTeks();
            form.isCek();
            form.setNoRm2(TNoRW.getText());
            form.setSize(internalFrame1.getWidth(), internalFrame1.getHeight());
            form.setLocationRelativeTo(internalFrame1);
            form.setVisible(true);
            this.setCursor(Cursor.getDefaultCursor());
        }// TODO add your handling code here:
    }//GEN-LAST:event_BtnRisikoJatuhGeriatriActionPerformed

    private void BtnCatatanPersalinanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCatatanPersalinanActionPerformed
        if (TNoRW.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, Silahkan anda pilih dulu salah satu datanya pada tabel...!!!");
        } else {
            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            akses.setform("DlgERM");
            RMCatatanPersalinan form = new RMCatatanPersalinan (null, false);
            form.emptTeks();
            form.isCek();
            form.setNoRm2(TNoRW.getText());
            form.setSize(internalFrame1.getWidth(), internalFrame1.getHeight());
            form.setLocationRelativeTo(internalFrame1);
            form.setVisible(true);
            this.setCursor(Cursor.getDefaultCursor());
        }// TODO add your handling code here:
    }//GEN-LAST:event_BtnCatatanPersalinanActionPerformed

    private void BtnSignInSbelummAnesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSignInSbelummAnesActionPerformed
        if (TNoRW.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, Silahkan anda pilih dulu salah satu datanya pada tabel...!!!");
        } else {
            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            akses.setform("DlgERM");
            RMSignInSebelumAnastesi form = new RMSignInSebelumAnastesi(null, false);
            form.emptTeks();
            form.isCek();
            form.setPasien(TNoRW.getText());
            form.setSize(internalFrame1.getWidth(), internalFrame1.getHeight());
            form.setLocationRelativeTo(internalFrame1);
            form.setVisible(true);
            this.setCursor(Cursor.getDefaultCursor());
        }// TODO add your handling code here:
    }//GEN-LAST:event_BtnSignInSbelummAnesActionPerformed

    private void BtnTimeOutSblumInsisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTimeOutSblumInsisiActionPerformed
        if (TNoRW.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, Silahkan anda pilih dulu salah satu datanya pada tabel...!!!");
        } else {
            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            akses.setform("DlgERM");
            RMTimeOutSebelumInsisi form = new RMTimeOutSebelumInsisi(null, false);
            form.emptTeks();
            form.isCek();
            form.setPasien(TNoRW.getText());
            form.setSize(internalFrame1.getWidth(), internalFrame1.getHeight());
            form.setLocationRelativeTo(internalFrame1);
            form.setVisible(true);
            this.setCursor(Cursor.getDefaultCursor());
        }// TODO add your handling code here:
    }//GEN-LAST:event_BtnTimeOutSblumInsisiActionPerformed

    private void BtnSOMenutupLukaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSOMenutupLukaActionPerformed
        if (TNoRW.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, Silahkan anda pilih dulu salah satu datanya pada tabel...!!!");
        } else {
            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            akses.setform("DlgERM");
            RMSignOutSebelumMenutupLuka form = new RMSignOutSebelumMenutupLuka(null, false);
            form.emptTeks();
            form.isCek();
            form.setPasien(TNoRW.getText());
            form.setSize(internalFrame1.getWidth(), internalFrame1.getHeight());
            form.setLocationRelativeTo(internalFrame1);
            form.setVisible(true);
            this.setCursor(Cursor.getDefaultCursor());
        }// TODO add your handling code here:
    }//GEN-LAST:event_BtnSOMenutupLukaActionPerformed

    private void BtnChcklisPostOPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnChcklisPostOPActionPerformed
        if (TNoRW.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, Silahkan anda pilih dulu salah satu datanya pada tabel...!!!");
        } else {
            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            akses.setform("DlgERM");
            RMChecklistPostOperasi form = new RMChecklistPostOperasi(null, false);
            form.emptTeks();
            form.isCek();
            form.setPasien(TNoRW.getText());
            form.setSize(internalFrame1.getWidth(), internalFrame1.getHeight());
            form.setLocationRelativeTo(internalFrame1);
            form.setVisible(true);
            this.setCursor(Cursor.getDefaultCursor());
        }// TODO add your handling code here:
    }//GEN-LAST:event_BtnChcklisPostOPActionPerformed

    private void BtnAwalKepRanapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAwalKepRanapActionPerformed
        if (TNoRW.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, Silahkan anda pilih dulu salah satu datanya pada tabel...!!!");
        } else {
            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            akses.setform("DlgERM");
            RMPenilaianAwalKeperawatanRanap form = new RMPenilaianAwalKeperawatanRanap(null, false);
            form.emptTeks();
            form.isCek();
            form.setNoRm2(TNoRW.getText(), TNoRM.getText());
            form.setSize(internalFrame1.getWidth(), internalFrame1.getHeight());
            form.setLocationRelativeTo(internalFrame1);
            form.setVisible(true);
            this.setCursor(Cursor.getDefaultCursor());
        }// TODO add your handling code here:
    }//GEN-LAST:event_BtnAwalKepRanapActionPerformed

    private void BtnAwalKebidRanapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAwalKebidRanapActionPerformed
        if (TNoRW.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, Silahkan anda pilih dulu salah satu datanya pada tabel...!!!");
        } else {
            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            akses.setform("DlgERM");
            RMPenilaianAwalKeperawatanKebidananRanap form = new RMPenilaianAwalKeperawatanKebidananRanap(null, false);
            form.emptTeks();
            form.isCek();
            form.setNoRm2(TNoRW.getText(), TNoRM.getText());
            form.setSize(internalFrame1.getWidth(), internalFrame1.getHeight());
            form.setLocationRelativeTo(internalFrame1);
            form.setVisible(true);
            this.setCursor(Cursor.getDefaultCursor());
        }// TODO add your handling code here:
    }//GEN-LAST:event_BtnAwalKebidRanapActionPerformed

    private void BtnAwalKepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAwalKepActionPerformed
        if (TNoRW.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, Silahkan anda pilih dulu salah satu datanya pada tabel...!!!");
        } else {
            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            akses.setform("DlgERM");
            RMPenilaianAwalKeperawatanRanap form = new RMPenilaianAwalKeperawatanRanap(null, false);
            form.emptTeks();
            form.isCek();
            form.setNoRm2(TNoRW.getText(), TNoRM.getText());
            form.setSize(internalFrame1.getWidth(), internalFrame1.getHeight());
            form.setLocationRelativeTo(internalFrame1);
            form.setVisible(true);
            this.setCursor(Cursor.getDefaultCursor());
        }// TODO add your handling code here:
    }//GEN-LAST:event_BtnAwalKepActionPerformed

    private void BtnKeluarHCUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKeluarHCUActionPerformed
        if (TNoRW.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, Silahkan anda pilih dulu salah satu datanya pada tabel...!!!");
        } else {
            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            akses.setform("DlgERM");
            RMChecklistKriteriaKeluarHCU form = new RMChecklistKriteriaKeluarHCU (null, false);
            form.emptTeks();
            form.isCek();
            form.setNoRm2(TNoRW.getText());
            form.setSize(internalFrame1.getWidth(), internalFrame1.getHeight());
            form.setLocationRelativeTo(internalFrame1);
            form.setVisible(true);
            this.setCursor(Cursor.getDefaultCursor());
        }// TODO add your handling code here:
    }//GEN-LAST:event_BtnKeluarHCUActionPerformed

    private void BtnMasukHCUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMasukHCUActionPerformed
        if (TNoRW.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, Silahkan anda pilih dulu salah satu datanya pada tabel...!!!");
        } else {
            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            akses.setform("DlgERM");
            RMChecklistKriteriaMasukHCU form = new RMChecklistKriteriaMasukHCU (null, false);
            form.emptTeks();
            form.isCek();
            form.setNoRm2(TNoRW.getText());
            form.setSize(internalFrame1.getWidth(), internalFrame1.getHeight());
            form.setLocationRelativeTo(internalFrame1);
            form.setVisible(true);
            this.setCursor(Cursor.getDefaultCursor());
        }// TODO add your handling code here:
    }//GEN-LAST:event_BtnMasukHCUActionPerformed

    private void BtnKeluarICUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKeluarICUActionPerformed
        if (TNoRW.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, Silahkan anda pilih dulu salah satu datanya pada tabel...!!!");
        } else {
            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            akses.setform("DlgERM");
            RMChecklistKriteriaKeluarICU form = new RMChecklistKriteriaKeluarICU (null, false);
            form.emptTeks();
            form.isCek();
            form.setNoRm2(TNoRW.getText());
            form.setSize(internalFrame1.getWidth(), internalFrame1.getHeight());
            form.setLocationRelativeTo(internalFrame1);
            form.setVisible(true);
            this.setCursor(Cursor.getDefaultCursor());
        }// TODO add your handling code here:
    }//GEN-LAST:event_BtnKeluarICUActionPerformed

    private void BtnMasukICUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMasukICUActionPerformed
        if (TNoRW.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, Silahkan anda pilih dulu salah satu datanya pada tabel...!!!");
        } else {
            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            akses.setform("DlgERM");
            RMChecklistKriteriaMasukICU form = new RMChecklistKriteriaMasukICU (null, false);
            form.emptTeks();
            form.isCek();
            form.setNoRm2(TNoRW.getText());
            form.setSize(internalFrame1.getWidth(), internalFrame1.getHeight());
            form.setLocationRelativeTo(internalFrame1);
            form.setVisible(true);
            this.setCursor(Cursor.getDefaultCursor());
        }// TODO add your handling code here:
    }//GEN-LAST:event_BtnMasukICUActionPerformed

    private void BtnVentilatorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVentilatorActionPerformed
        if (TNoRW.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, Silahkan anda pilih dulu salah satu datanya pada tabel...!!!");
        } else {
            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            akses.setform("DlgERM");
            RMDataCatatanObservasiVentilator form = new RMDataCatatanObservasiVentilator (null, false);
            form.emptTeks();
            form.isCek();
            form.setNoRm2(TNoRW.getText());
            form.setSize(internalFrame1.getWidth(), internalFrame1.getHeight());
            form.setLocationRelativeTo(internalFrame1);
            form.setVisible(true);
            this.setCursor(Cursor.getDefaultCursor());
        }// TODO add your handling code here:
    }//GEN-LAST:event_BtnVentilatorActionPerformed

    private void BtnGDSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGDSActionPerformed
        if (TNoRW.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, Silahkan anda pilih dulu salah satu datanya pada tabel...!!!");
        } else {
            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            akses.setform("DlgERM");
            RMDataCatatanCekGDS form = new RMDataCatatanCekGDS (null, false);
            form.emptTeks();
            form.isCek();
            form.setNoRm2(TNoRW.getText());
            form.setSize(internalFrame1.getWidth(), internalFrame1.getHeight());
            form.setLocationRelativeTo(internalFrame1);
            form.setVisible(true);
            this.setCursor(Cursor.getDefaultCursor());
        }// TODO add your handling code here:
    }//GEN-LAST:event_BtnGDSActionPerformed

    private void BtnReakasiTranfusiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnReakasiTranfusiActionPerformed
        if (TNoRW.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, Silahkan anda pilih dulu salah satu datanya pada tabel...!!!");
        } else {
            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            akses.setform("DlgERM");
            RMDataMonitoringReaksiTranfusi form = new RMDataMonitoringReaksiTranfusi (null, false);
            form.emptTeks();
            form.isCek();
            form.setNoRm2(TNoRW.getText());
            form.setSize(internalFrame1.getWidth(), internalFrame1.getHeight());
            form.setLocationRelativeTo(internalFrame1);
            form.setVisible(true);
            this.setCursor(Cursor.getDefaultCursor());
        }// TODO add your handling code here:
    }//GEN-LAST:event_BtnReakasiTranfusiActionPerformed

    private void BtnRencanaPemulanganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRencanaPemulanganActionPerformed
        if (TNoRW.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, Silahkan anda pilih dulu salah satu datanya pada tabel...!!!");
        } else {
            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            akses.setform("DlgERM");
            RMPerencanaanPemulangan form = new RMPerencanaanPemulangan (null, false);
            form.emptTeks();
            form.isCek();
            form.setNoRm2(TNoRW.getText());
            form.setSize(internalFrame1.getWidth(), internalFrame1.getHeight());
            form.setLocationRelativeTo(internalFrame1);
            form.setVisible(true);
            this.setCursor(Cursor.getDefaultCursor());
        }// TODO add your handling code here:
    }//GEN-LAST:event_BtnRencanaPemulanganActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            DlgERM dialog = new DlgERM(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private widget.ButtonBig BtnAwalKebidRanap;
    private widget.ButtonBig BtnAwalKep;
    private widget.ButtonBig BtnAwalKepAnak;
    private widget.ButtonBig BtnAwalKepNeonatus;
    private widget.ButtonBig BtnAwalKepRanap;
    private widget.ButtonBig BtnAwalMedisInap;
    private widget.ButtonBig BtnCatatanPersalinan;
    private widget.ButtonBig BtnChcklisPostOP;
    private widget.ButtonBig BtnGDS;
    private widget.Button BtnKeluar;
    private widget.ButtonBig BtnKeluarHCU;
    private widget.ButtonBig BtnKeluarICU;
    private widget.ButtonBig BtnMasukHCU;
    private widget.ButtonBig BtnMasukICU;
    private widget.ButtonBig BtnMedisKandungan;
    private widget.ButtonBig BtnMedisNeonatus;
    private widget.ButtonBig BtnMonitoringEWSAnak;
    private widget.ButtonBig BtnMonitoringEWSDewasa;
    private widget.ButtonBig BtnMonitoringEWSNeonatus;
    private widget.ButtonBig BtnMonitoringEWSObstetri;
    private widget.ButtonBig BtnPreOperasi;
    private widget.ButtonBig BtnReakasiTranfusi;
    private widget.Button BtnRefres;
    private widget.ButtonBig BtnRencanaPemulangan;
    private widget.ButtonBig BtnResumeInap;
    private widget.ButtonBig BtnRisikoJatuh;
    private widget.ButtonBig BtnRisikoJatuhAnak;
    private widget.ButtonBig BtnRisikoJatuhGeriatri;
    private widget.ButtonBig BtnSOMenutupLuka;
    private widget.ButtonBig BtnSignInSbelummAnes;
    private widget.ButtonBig BtnTimeOutSblumInsisi;
    private widget.ButtonBig BtnTransferRuang;
    private widget.ButtonBig BtnVentilator;
    private widget.PanelBiasa FormInput;
    private widget.PanelBiasa FormInput1;
    private widget.PanelBiasa FormInput2;
    private widget.TextBox KdDPJP;
    private widget.TextBox KdPetugas;
    private widget.TextBox KdPetugas2;
    private widget.TextBox NmDPJP;
    private widget.TextBox NmPetugas;
    private widget.TextBox NmPetugas2;
    private widget.TextBox TNmPasien;
    private widget.TextBox TNoRM;
    private widget.TextBox TNoRW;
    private javax.swing.JTabbedPane TabRekamMedis;
    private widget.TextBox TtglMasuk;
    private javax.swing.JDialog WindowDPJPranap;
    private widget.Button btnDPJP;
    private widget.InternalFrame internalFrame1;
    private widget.InternalFrame internalFrame15;
    private widget.InternalFrame internalFrame4;
    private widget.Label jLabel13;
    private widget.Label jLabel3;
    private widget.Label jLabel4;
    private widget.Label label9;
    private widget.panelisi panelisi1;
    private widget.ScrollPane scrollInput;
    private widget.ScrollPane scrollInput1;
    private widget.ScrollPane scrollInput2;
    // End of variables declaration//GEN-END:variables

    
    private void isCek() {
        BtnResumeInap.setEnabled(akses.getdata_resume_pasien());
        BtnPreOperasi.setEnabled(akses.getpenilaian_pre_operasi());
        BtnSignInSbelummAnes.setEnabled(akses.getsignin_sebelum_anestesi());
        BtnTimeOutSblumInsisi.setEnabled(akses.gettimeout_sebelum_insisi());
        BtnSOMenutupLuka.setEnabled(akses.getsignout_sebelum_menutup_luka());
        BtnChcklisPostOP.setEnabled(akses.getchecklist_post_operasi());
        BtnAwalMedisInap.setEnabled(akses.getpenilaian_awal_medis_ranap());
        BtnMedisKandungan.setEnabled(akses.getpenilaian_awal_medis_ranap());
        BtnMedisNeonatus.setEnabled(akses.getpenilaian_awal_medis_ranap());
        BtnAwalKepRanap.setEnabled(akses.getpenilaian_awal_keperawatan_ranap());
        BtnAwalKebidRanap.setEnabled(akses.getpenilaian_awal_keperawatan_ranapkebidanan());
        BtnAwalKepAnak.setEnabled(akses.getpenilaian_awal_keperawatan_ranap_bayi());
        BtnAwalKepNeonatus.setEnabled(akses.getpenilaian_awal_keperawatan_ranap_neonatus());
        BtnTransferRuang.setEnabled(akses.gettransfer_pasien_antar_ruang());
        BtnMonitoringEWSDewasa.setEnabled(akses.getpemantauan_pews_dewasa());
        BtnMonitoringEWSAnak.setEnabled(akses.getpemantauan_pews_anak());
        BtnMonitoringEWSNeonatus.setEnabled(akses.getpemantauan_ews_neonatus());
        BtnMonitoringEWSObstetri.setEnabled(akses.getpemantauan_meows_obstetri());
        BtnRisikoJatuh.setEnabled(akses.getpenilaian_lanjutan_resiko_jatuh_dewasa());
        BtnRisikoJatuhAnak.setEnabled(akses.getpenilaian_lanjutan_resiko_jatuh_anak());
        BtnRisikoJatuhGeriatri.setEnabled(akses.getpenilaian_lanjutan_resiko_jatuh_geriatri());
        BtnCatatanPersalinan.setEnabled(akses.getcatatan_persalinan());
        BtnRencanaPemulangan.setEnabled(akses.getperencanaan_pemulangan());
        BtnAwalKep.setEnabled(akses.getpenilaian_awal_keperawatan_ranap());
        BtnKeluarHCU.setEnabled(akses.getchecklist_kriteria_keluar_hcu());
        BtnMasukHCU.setEnabled(akses.getchecklist_kriteria_masuk_hcu());
        BtnKeluarICU.setEnabled(akses.getchecklist_kriteria_keluar_icu());
        BtnMasukICU.setEnabled(akses.getchecklist_kriteria_masuk_icu());
        BtnVentilator.setEnabled(akses.getcatatan_observasi_ventilator());
        BtnGDS.setEnabled(akses.getcatatan_cek_gds());
        BtnReakasiTranfusi.setEnabled(akses.getmonitoring_reaksi_tranfusi());
    }
    
    public void setData(String norw, String norm, String nmpasien,
            String status, String kmr,
            String tglmsk) {
        
        TNoRW.setText(norw);
        TNoRM.setText(norm);
        TNmPasien.setText(nmpasien);
        stts = status;
        //kdkamar = kdkmr;
        TtglMasuk.setText(tglmsk);
        tombolCek(norw);
    }
    
    private void tombolCek(String norawat) {
        if (Sequel.cariInteger("select count(-1) from resume_pasien_ranap where no_rawat='" + norawat + "'") == 0) {
            BtnResumeInap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/1360485642_edit-notes.png")));
            BtnResumeInap.setToolTipText("RESUME Pasien Rawat Inap BELUM diisi oleh dokter DPJP..!!!");
        } else {
            BtnResumeInap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/verif.png")));
            BtnResumeInap.setToolTipText("RESUME Pasien Rawat Inap SUDAH diisi oleh dokter DPJP..!!!");
        }
        if (Sequel.cariInteger("select count(-1) from penilaian_medis_ranap where no_rawat='" + norawat + "'") == 0) {
            BtnAwalMedisInap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/doctor2.png")));
            BtnAwalMedisInap.setToolTipText("Asesmen Awal Medis Pasien Rawat Inap BELUM diisi oleh dokter DPJP..!!!");
        } else {
            BtnAwalMedisInap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/verif.png")));
            BtnAwalMedisInap.setToolTipText("Asesmen Awal Medis Pasien Rawat Inap SUDAH diisi oleh dokter DPJP..!!!");
        }
        if (Sequel.cariInteger("select count(-1) from penilaian_medis_ranap_kandungan where no_rawat='" + norawat + "'") == 0) {
            BtnMedisKandungan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/doctor2.png")));
            BtnMedisKandungan.setToolTipText("Asesmen Awal Medis Kandungan Pasien Rawat Inap BELUM diisi oleh dokter DPJP..!!!");
        } else {
            BtnMedisKandungan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/verif.png")));
            BtnMedisKandungan.setToolTipText("Asesmen Awal Medis Kandungan Pasien Rawat Inap SUDAH diisi oleh dokter DPJP..!!!");
        }
        if (Sequel.cariInteger("select count(-1) from penilaian_medis_ranap_neonatus where no_rawat='" + norawat + "'") == 0) {
            BtnMedisNeonatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/doctor2.png")));
            BtnMedisNeonatus.setToolTipText("Asesmen Awal Medis Neonatus Pasien Rawat Inap BELUM diisi oleh dokter DPJP..!!!");
        } else {
            BtnMedisNeonatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/verif.png")));
            BtnMedisNeonatus.setToolTipText("Asesmen Awal Medis Neonatus Pasien Rawat Inap SUDAH diisi oleh dokter DPJP..!!!");
        }
        if (Sequel.cariInteger("select count(-1) from penilaian_awal_keperawatan_ranap where no_rawat='" + norawat + "'") == 0) {
            BtnAwalKepRanap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/2620509_employee_job_note_seeker_unemployee_icon.png")));
            BtnAwalKepRanap.setToolTipText("Asesmen Awal Keperawatan Pasien Rawat Inap BELUM diisi..!!!");
        } else {
            BtnAwalKepRanap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/verif.png")));
            BtnAwalKepRanap.setToolTipText("Asesmen Awal Keperawatan Pasien Rawat Inap SUDAH diisi..!!!");
        }
        if (Sequel.cariInteger("select count(-1) from penilaian_awal_keperawatan_kebidanan_ranap where no_rawat='" + norawat + "'") == 0) {
            BtnAwalKebidRanap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/2620509_employee_job_note_seeker_unemployee_icon.png")));
            BtnAwalKebidRanap.setToolTipText("Asesmen Awal Kebidanan Pasien Rawat Inap BELUM diisi..!!!");
        } else {
            BtnAwalKebidRanap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/verif.png")));
            BtnAwalKebidRanap.setToolTipText("Asesmen Awal Kebidanan Pasien Rawat Inap SUDAH diisi..!!!");
        }
        if (Sequel.cariInteger("select count(-1) from penilaian_awal_keperawatan_ranap_bayi where no_rawat='" + norawat + "'") == 0) {
            BtnAwalKepAnak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/2620509_employee_job_note_seeker_unemployee_icon.png")));
            BtnAwalKepAnak.setToolTipText("Asesmen Awal Keperawatan Pasien Anak Rawat Inap BELUM diisi..!!!");
        } else {
            BtnAwalKepAnak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/verif.png")));
            BtnAwalKepAnak.setToolTipText("Asesmen Awal Keperawatan Pasien Anak Rawat Inap SUDAH diisi..!!!");
        }
        if (Sequel.cariInteger("select count(-1) from penilaian_awal_keperawatan_ranap_neonatus where no_rawat='" + norawat + "'") == 0) {
            BtnAwalKepNeonatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/2620509_employee_job_note_seeker_unemployee_icon.png")));
            BtnAwalKepNeonatus.setToolTipText("Asesmen Awal Keperawatan Pasien Neonatus Rawat Inap BELUM diisi..!!!");
        } else {
            BtnAwalKepNeonatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/verif.png")));
            BtnAwalKepNeonatus.setToolTipText("Asesmen Awal Keperawatan Pasien Neonatus Rawat Inap SUDAH diisi..!!!");
        }
        if (Sequel.cariInteger("select count(-1) from transfer_pasien_antar_ruang where no_rawat='" + norawat + "'") == 0) {
            BtnTransferRuang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/1481002123_wheelchair.png")));
            BtnTransferRuang.setToolTipText("Lembar Transfer Pasien Rawat Inap BELUM diisi..!!!");
        } else {
            BtnTransferRuang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/verif.png")));
            BtnTransferRuang.setToolTipText("Lembar Transfer Pasien Rawat Inap SUDAH diisi..!!!");
        }
        if (Sequel.cariInteger("select count(-1) from pemantauan_pews_dewasa where no_rawat='" + norawat + "'") == 0) {
            BtnMonitoringEWSDewasa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/if_gtk-find-and-replace_39047.png")));
            BtnMonitoringEWSDewasa.setToolTipText("Monitoring EWS Pasien Rawat Inap BELUM diisi..!!!");
        } else {
            BtnMonitoringEWSDewasa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/verif.png")));
            BtnMonitoringEWSDewasa.setToolTipText("Monitoring EWS Pasien Rawat Inap SUDAH diisi..!!!");
        }
        if (Sequel.cariInteger("select count(-1) from pemantauan_pews_anak where no_rawat='" + norawat + "'") == 0) {
            BtnMonitoringEWSAnak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/if_gtk-find-and-replace_39047.png")));
            BtnMonitoringEWSAnak.setToolTipText("Monitoring EWS Pasien Anak Rawat Inap BELUM diisi..!!!");
        } else {
            BtnMonitoringEWSAnak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/verif.png")));
            BtnMonitoringEWSAnak.setToolTipText("Monitoring EWS Pasien Anak Rawat Inap SUDAH diisi..!!!");
        }
        if (Sequel.cariInteger("select count(-1) from pemantauan_ews_neonatus where no_rawat='" + norawat + "'") == 0) {
            BtnMonitoringEWSNeonatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/if_gtk-find-and-replace_39047.png")));
            BtnMonitoringEWSNeonatus.setToolTipText("Monitoring EWS Pasien Neonatus Rawat Inap BELUM diisi..!!!");
        } else {
            BtnMonitoringEWSNeonatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/verif.png")));
            BtnMonitoringEWSNeonatus.setToolTipText("Monitoring EWS Pasien Neonatus Rawat Inap SUDAH diisi..!!!");
        }
        if (Sequel.cariInteger("select count(-1) from pemantauan_meows_obstetri where no_rawat='" + norawat + "'") == 0) {
            BtnMonitoringEWSObstetri.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/if_gtk-find-and-replace_39047.png")));
            BtnMonitoringEWSObstetri.setToolTipText("Monitoring EWS Pasien Obstetri Rawat Inap BELUM diisi..!!!");
        } else {
            BtnMonitoringEWSObstetri.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/verif.png")));
            BtnMonitoringEWSObstetri.setToolTipText("Monitoring EWS Pasien Obstetri Rawat Inap SUDAH diisi..!!!");
        }
        if (Sequel.cariInteger("select count(-1) from penilaian_lanjutan_resiko_jatuh_dewasa where no_rawat='" + norawat + "'") == 0) {
            BtnRisikoJatuh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/iconfinder_software-update-urgent_118956.png")));
            BtnRisikoJatuh.setToolTipText("Penilaian Lanjutan Risiko Jatuh Pasien Rawat Inap BELUM diisi..!!!");
        } else {
            BtnRisikoJatuh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/verif.png")));
            BtnRisikoJatuh.setToolTipText("Penilaian Lanjutan Risiko Jatuh Pasien Rawat Inap SUDAH diisi..!!!");
        }
        if (Sequel.cariInteger("select count(-1) from penilaian_lanjutan_resiko_jatuh_anak where no_rawat='" + norawat + "'") == 0) {
            BtnRisikoJatuhAnak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/iconfinder_software-update-urgent_118956.png")));
            BtnRisikoJatuhAnak.setToolTipText("Penilaian Lanjutan Risiko Jatuh Pasien Anak Rawat Inap BELUM diisi..!!!");
        } else {
            BtnRisikoJatuhAnak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/verif.png")));
            BtnRisikoJatuhAnak.setToolTipText("Penilaian Lanjutan Risiko Jatuh Pasien Anak Rawat Inap SUDAH diisi..!!!");
        }
        if (Sequel.cariInteger("select count(-1) from penilaian_lanjutan_resiko_jatuh_geriatri where no_rawat='" + norawat + "'") == 0) {
            BtnRisikoJatuhGeriatri.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/iconfinder_software-update-urgent_118956.png")));
            BtnRisikoJatuhGeriatri.setToolTipText("Penilaian Lanjutan Risiko Jatuh Pasien Geriatri Rawat Inap BELUM diisi..!!!");
        } else {
            BtnRisikoJatuhGeriatri.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/verif.png")));
            BtnRisikoJatuhGeriatri.setToolTipText("Penilaian Lanjutan Risiko Jatuh Pasien Geriatri Rawat Inap SUDAH diisi..!!!");
        }
        if (Sequel.cariInteger("select count(-1) from catatan_persalinan where no_rawat='" + norawat + "'") == 0) {
            BtnCatatanPersalinan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/6771569_education_learning_pencil_school_signature_icon.png")));
            BtnCatatanPersalinan.setToolTipText("Catatan Persalinan Pasien BELUM diisi..!!!");
        } else {
            BtnCatatanPersalinan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/verif.png")));
            BtnCatatanPersalinan.setToolTipText("Catatan Persalinan Pasien SUDAH diisi..!!!");
        }
        if (Sequel.cariInteger("select count(-1) from perencanaan_pemulangan where no_rawat='" + norawat + "'") == 0) {
            BtnRencanaPemulangan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/1360485642_edit-notes.png")));
            BtnRencanaPemulangan.setToolTipText("Catatan Persalinan Pasien BELUM diisi..!!!");
        } else {
            BtnRencanaPemulangan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/verif.png")));
            BtnRencanaPemulangan.setToolTipText("Catatan Persalinan Pasien SUDAH diisi..!!!");
        }
        if (Sequel.cariInteger("select count(-1) from penilaian_awal_keperawatan_ranap where no_rawat='" + norawat + "'") == 0) {
            BtnAwalKep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/2620509_employee_job_note_seeker_unemployee_icon.png")));
            BtnAwalKep.setToolTipText("Asesmen Awal Keperawatan Pasien Rawat Inap BELUM diisi..!!!");
        } else {
            BtnAwalKep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/verif.png")));
            BtnAwalKep.setToolTipText("Asesmen Awal Keperawatan Pasien Rawat Inap SUDAH diisi..!!!");
        }
        if (Sequel.cariInteger("select count(-1) from checklist_kriteria_keluar_hcu where no_rawat='" + norawat + "'") == 0) {
            BtnKeluarHCU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/2620509_employee_job_note_seeker_unemployee_icon.png")));
            BtnKeluarHCU.setToolTipText("Catatan Keluar HCU Pasien Rawat Inap BELUM diisi..!!!");
        } else {
            BtnKeluarHCU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/verif.png")));
            BtnKeluarHCU.setToolTipText("Catatan Keluar HCU Pasien Rawat Inap SUDAH diisi..!!!");
        }
        if (Sequel.cariInteger("select count(-1) from checklist_kriteria_masuk_hcu where no_rawat='" + norawat + "'") == 0) {
            BtnMasukHCU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/2620509_employee_job_note_seeker_unemployee_icon.png")));
            BtnMasukHCU.setToolTipText("Catatan Masuk HCU Pasien Rawat Inap BELUM diisi..!!!");
        } else {
            BtnMasukHCU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/verif.png")));
            BtnMasukHCU.setToolTipText("Catatan Masuk HCU Pasien Rawat Inap SUDAH diisi..!!!");
        }
        if (Sequel.cariInteger("select count(-1) from checklist_kriteria_keluar_icu where no_rawat='" + norawat + "'") == 0) {
            BtnKeluarICU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/2620509_employee_job_note_seeker_unemployee_icon.png")));
            BtnKeluarICU.setToolTipText("Catatan Keluar ICU Pasien Rawat Inap BELUM diisi..!!!");
        } else {
            BtnKeluarICU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/verif.png")));
            BtnKeluarICU.setToolTipText("Catatan Keluar ICU Pasien Rawat Inap SUDAH diisi..!!!");
        }
        if (Sequel.cariInteger("select count(-1) from checklist_kriteria_masuk_icu where no_rawat='" + norawat + "'") == 0) {
            BtnMasukICU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/2620509_employee_job_note_seeker_unemployee_icon.png")));
            BtnMasukICU.setToolTipText("Catatan Masuk ICU Pasien Rawat Inap BELUM diisi..!!!");
        } else {
            BtnMasukICU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/verif.png")));
            BtnMasukICU.setToolTipText("Catatan Masuk ICU Pasien Rawat Inap SUDAH diisi..!!!");
        }
        if (Sequel.cariInteger("select count(-1) from catatan_observasi_ventilator where no_rawat='" + norawat + "'") == 0) {
            BtnVentilator.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/6088631_bed_hospital_icu_medical_treatment_icon.png")));
            BtnVentilator.setToolTipText("Catatan Ventilator Pasien Rawat Inap BELUM diisi..!!!");
        } else {
            BtnVentilator.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/verif.png")));
            BtnVentilator.setToolTipText("Catatan Ventilator Pasien Rawat Inap SUDAH diisi..!!!");
        }
        if (Sequel.cariInteger("select count(-1) from catatan_cek_gds where no_rawat='" + norawat + "'") == 0) {
            BtnGDS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/6427847_information_note_notebook_sheet_icon.png")));
            BtnGDS.setToolTipText("Catatan GDS Pasien Rawat Inap BELUM diisi..!!!");
        } else {
            BtnGDS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/verif.png")));
            BtnGDS.setToolTipText("Catatan GDS Pasien Rawat Inap SUDAH diisi..!!!");
        }
        if (Sequel.cariInteger("select count(-1) from monitoring_reaksi_tranfusi where no_rawat='" + norawat + "'") == 0) {
            BtnReakasiTranfusi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/6088722_blood_bottle_packet_icon.png")));
            BtnReakasiTranfusi.setToolTipText("Reaksi Tranfusi Pasien Rawat Inap BELUM diisi..!!!");
        } else {
            BtnReakasiTranfusi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/verif.png")));
            BtnReakasiTranfusi.setToolTipText("Reaksi Tranfusi Pasien Rawat Inap SUDAH diisi..!!!");
        }
    }
}
