/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DlgPenyakit.java
 *
 * Created on May 23, 2010, 12:57:16 AM
 */

package rekammedis;

import fungsi.WarnaTable;
import fungsi.batasInput;
import fungsi.koneksiDB;
import fungsi.validasi;
import java.awt.Dimension;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JTable;
import javax.swing.event.DocumentEvent;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

public final class RMCariDiagnosa1 extends javax.swing.JDialog {
    private final DefaultTableModel tabMode;
    private validasi Valid=new validasi();
    private Connection koneksi=koneksiDB.condb();
    private PreparedStatement ps;
    private ResultSet rs;
    private String norawat="";
    private int z=0;
    private int nomorUrut = 1; 

    public RMCariDiagnosa1(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocation(10,2);
        setSize(656,250);

        Object[] row={"P","Kode","Nama Penyakit","Status","Urut"};
        
        tabMode=new DefaultTableModel(null,row){
        @Override public Class getColumnClass(int columnIndex) {
           if (columnIndex == 0) {
               return Boolean.class;
           } else {
               return super.getColumnClass(columnIndex);
           }
        }

        @Override public boolean isCellEditable(int rowIndex, int colIndex){
           return false; 
        }
   };
        
        tbKamar.setModel(tabMode);
        tbKamar.setPreferredScrollableViewportSize(new Dimension(500,500));
        tbKamar.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);

        for (z= 0; z < 5; z++) {
            TableColumn column = tbKamar.getColumnModel().getColumn(z);
            if(z==0){
                column.setPreferredWidth(20);
            }else if(z==1){
                column.setPreferredWidth(65);
            }else if(z==2){
                column.setPreferredWidth(450); 
            }else if(z==3){
                column.setPreferredWidth(50);
            }else if(z==4){
                column.setPreferredWidth(40); 
            }
        }
        
        tbKamar.setDefaultRenderer(Object.class, new WarnaTable());
        TCari.setDocument(new batasInput((byte)100).getKata(TCari));
        
        if(koneksiDB.CARICEPAT().equals("aktif")){
            TCari.getDocument().addDocumentListener(new javax.swing.event.DocumentListener(){
                @Override
                public void insertUpdate(DocumentEvent e) {
                    if(TCari.getText().length()>2){
                        tampil();
                    }
                }
                @Override
                public void removeUpdate(DocumentEvent e) {
                    if(TCari.getText().length()>2){
                        tampil();
                    }
                }
                @Override
                public void changedUpdate(DocumentEvent e) {
                    if(TCari.getText().length()>2){
                        tampil();
                    }
                }
            });
        }
    }
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        internalFrame1 = new widget.InternalFrame();
        Scroll = new widget.ScrollPane();
        tbKamar = new widget.Table();
        panelisi3 = new widget.panelisi();
        label9 = new widget.Label();
        TCari = new widget.TextBox();
        BtnCari = new widget.Button();
        BtnAll = new widget.Button();
        label10 = new widget.Label();
        LCount = new widget.Label();
        BtnKeluar = new widget.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        internalFrame1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 245, 235)), "::[ Riwayat Pemeriksaan ]::", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(50, 50, 50))); // NOI18N
        internalFrame1.setName("internalFrame1"); // NOI18N
        internalFrame1.setLayout(new java.awt.BorderLayout(1, 1));

        Scroll.setName("Scroll"); // NOI18N
        Scroll.setOpaque(true);

        tbKamar.setAutoCreateRowSorter(true);
        tbKamar.setName("tbKamar"); // NOI18N
        tbKamar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbKamarMouseClicked(evt);
            }
        });
        tbKamar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tbKamarKeyPressed(evt);
            }
        });
        Scroll.setViewportView(tbKamar);

        internalFrame1.add(Scroll, java.awt.BorderLayout.CENTER);

        panelisi3.setName("panelisi3"); // NOI18N
        panelisi3.setPreferredSize(new java.awt.Dimension(100, 43));
        panelisi3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 4, 9));

        label9.setText("Key Word :");
        label9.setName("label9"); // NOI18N
        label9.setPreferredSize(new java.awt.Dimension(68, 23));
        panelisi3.add(label9);

        TCari.setName("TCari"); // NOI18N
        TCari.setPreferredSize(new java.awt.Dimension(300, 23));
        TCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TCariActionPerformed(evt);
            }
        });
        TCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TCariKeyPressed(evt);
            }
        });
        panelisi3.add(TCari);

        BtnCari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/accept.png"))); // NOI18N
        BtnCari.setMnemonic('1');
        BtnCari.setToolTipText("Alt+1");
        BtnCari.setName("BtnCari"); // NOI18N
        BtnCari.setPreferredSize(new java.awt.Dimension(28, 23));
        BtnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCariActionPerformed(evt);
            }
        });
        BtnCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnCariKeyPressed(evt);
            }
        });
        panelisi3.add(BtnCari);

        BtnAll.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Search-16x16.png"))); // NOI18N
        BtnAll.setMnemonic('2');
        BtnAll.setToolTipText("2Alt+2");
        BtnAll.setName("BtnAll"); // NOI18N
        BtnAll.setPreferredSize(new java.awt.Dimension(28, 23));
        BtnAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAllActionPerformed(evt);
            }
        });
        BtnAll.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnAllKeyPressed(evt);
            }
        });
        panelisi3.add(BtnAll);

        label10.setText("Record :");
        label10.setName("label10"); // NOI18N
        label10.setPreferredSize(new java.awt.Dimension(60, 23));
        panelisi3.add(label10);

        LCount.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LCount.setText("0");
        LCount.setName("LCount"); // NOI18N
        LCount.setPreferredSize(new java.awt.Dimension(50, 23));
        panelisi3.add(LCount);

        BtnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/exit.png"))); // NOI18N
        BtnKeluar.setMnemonic('4');
        BtnKeluar.setToolTipText("Alt+4");
        BtnKeluar.setName("BtnKeluar"); // NOI18N
        BtnKeluar.setPreferredSize(new java.awt.Dimension(28, 23));
        BtnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKeluarActionPerformed(evt);
            }
        });
        panelisi3.add(BtnKeluar);

        internalFrame1.add(panelisi3, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(internalFrame1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void TCariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TCariKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            BtnCariActionPerformed(null);
        }else if(evt.getKeyCode()==KeyEvent.VK_PAGE_DOWN){
            BtnCari.requestFocus();
        }else if(evt.getKeyCode()==KeyEvent.VK_PAGE_UP){
            BtnKeluar.requestFocus();
        }else if(evt.getKeyCode()==KeyEvent.VK_UP){
            tbKamar.requestFocus();
        }
}//GEN-LAST:event_TCariKeyPressed

    private void BtnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCariActionPerformed
        tampil();
}//GEN-LAST:event_BtnCariActionPerformed

    private void BtnCariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnCariKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_SPACE){
            BtnCariActionPerformed(null);
        }else{
            Valid.pindah(evt, TCari, BtnAll);
        }
}//GEN-LAST:event_BtnCariKeyPressed

    private void BtnAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAllActionPerformed
        TCari.setText("");
        tampil();
}//GEN-LAST:event_BtnAllActionPerformed

    private void BtnAllKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnAllKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_SPACE){
            BtnAllActionPerformed(null);
        }else{
            Valid.pindah(evt, BtnCari, TCari);
        }
}//GEN-LAST:event_BtnAllKeyPressed

    private void tbKamarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbKamarMouseClicked
        if(tabMode.getRowCount()!=0){
        try {
            int row = tbKamar.getSelectedRow();
            int col = tbKamar.getSelectedColumn();
            
            if(col == 0){
                Object currentValue = tbKamar.getValueAt(row, 0);
                boolean isChecked = currentValue != null && Boolean.TRUE.equals(currentValue);
                boolean newValue = !isChecked;
                tbKamar.setValueAt(newValue, row, 0);
                
                if(newValue){
                    int jumlahAktif = 0;
                    int maxUrut = 0;
                    for(int i=0; i<tbKamar.getRowCount(); i++){
                        Object valUrut = tbKamar.getValueAt(i, 4);
                        if(valUrut != null && !valUrut.toString().equals("")){
                            jumlahAktif++;
                            try{
                                int n = Integer.parseInt(valUrut.toString());
                                if(n > maxUrut) maxUrut = n;
                            }catch(Exception e){}
                        }
                    }

                    if(jumlahAktif >= 5){
                        javax.swing.JOptionPane.showMessageDialog(null, "Maaf, maksimal hanya boleh memilih 5 diagnosa!");
                        tbKamar.setValueAt(false, row, 0); 
                        return;
                    }

                    tbKamar.setValueAt(String.valueOf(maxUrut + 1), row, 4);
                    
                } else {
                    String valUrut = (String) tbKamar.getValueAt(row, 4);
                    int urutanDihapus = 0;
                    if(valUrut != null && !valUrut.equals("")){
                        try{ urutanDihapus = Integer.parseInt(valUrut); }catch(Exception e){}
                    }
                    
                    tbKamar.setValueAt("", row, 4);
                    
                    if(urutanDihapus > 0){
                        for(int i=0; i<tbKamar.getRowCount(); i++){
                            Object valObj = tbKamar.getValueAt(i, 4);
                            if(valObj != null && !valObj.toString().equals("")){
                                try{
                                    int nilai = Integer.parseInt(valObj.toString());
                                    if(nilai > urutanDihapus){
                                        tbKamar.setValueAt(String.valueOf(nilai - 1), i, 4);
                                    }
                                }catch(Exception e){}
                            }
                        }
                    }
                }
            }
        } catch (Exception e) {
            System.out.println("Error : " + e);
        }
    }
}//GEN-LAST:event_tbKamarMouseClicked

    private void tbKamarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbKamarKeyPressed
        if(tabMode.getRowCount()!=0){
        if(evt.getKeyCode()==KeyEvent.VK_SPACE){
            dispose(); 
        }else if(evt.getKeyCode()==KeyEvent.VK_SHIFT){
            TCari.setText("");
            TCari.requestFocus();
        }
    }
}//GEN-LAST:event_tbKamarKeyPressed

    private void BtnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKeluarActionPerformed
        dispose();
    }//GEN-LAST:event_BtnKeluarActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        emptTeks();
    }//GEN-LAST:event_formWindowActivated

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        tampil();
    }//GEN-LAST:event_formWindowOpened

    private void TCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TCariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TCariActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            RMCariDiagnosa1 dialog = new RMCariDiagnosa1(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private widget.Button BtnAll;
    private widget.Button BtnCari;
    private widget.Button BtnKeluar;
    private widget.Label LCount;
    private widget.ScrollPane Scroll;
    private widget.TextBox TCari;
    private widget.InternalFrame internalFrame1;
    private widget.Label label10;
    private widget.Label label9;
    private widget.panelisi panelisi3;
    private widget.Table tbKamar;
    // End of variables declaration//GEN-END:variables

    public void tampil() {
        Valid.tabelKosong(tabMode);
        try {
            if (norawat.equals("")) {
                return;
            }

            ps = koneksi.prepareStatement(
                "select kd_diagnosa_utama, diagnosa_utama, " +
                "kd_diagnosa_sekunder, diagnosa_sekunder, " +
                "kd_diagnosa_sekunder2, diagnosa_sekunder2, " +
                "kd_diagnosa_sekunder3, diagnosa_sekunder3, " +
                "kd_diagnosa_sekunder4, diagnosa_sekunder4 " +
                "from resume_pasien_ranap where no_rawat=?");

            try {
                ps.setString(1, norawat);
                rs = ps.executeQuery();
                nomorUrut = 1;

                if (rs.next()) {
                    addDiagnosaToRow(rs.getString("kd_diagnosa_utama"), rs.getString("diagnosa_utama"), "Diagnosa Utama");
                    addDiagnosaToRow(rs.getString("kd_diagnosa_sekunder"), rs.getString("diagnosa_sekunder"), "Diagnosa Sekunder 1");
                    addDiagnosaToRow(rs.getString("kd_diagnosa_sekunder2"), rs.getString("diagnosa_sekunder2"), "Diagnosa Sekunder 2");
                    addDiagnosaToRow(rs.getString("kd_diagnosa_sekunder3"), rs.getString("diagnosa_sekunder3"), "Diagnosa Sekunder 3");
                    addDiagnosaToRow(rs.getString("kd_diagnosa_sekunder4"), rs.getString("diagnosa_sekunder4"), "Diagnosa Sekunder 4");
                }
            } catch (Exception ex) {
                System.out.println("Error Query: " + ex);
            } finally {
                if (rs != null) { rs.close(); }
                if (ps != null) { ps.close(); }
            }
        } catch (Exception e) {
            System.out.println("Notifikasi : " + e);
        }
        LCount.setText("" + tabMode.getRowCount());
    }

    private void addDiagnosaToRow(String kode, String nama, String statusLabel) {
        boolean kodeAda = kode != null && !kode.trim().equals("");
        boolean namaAda = nama != null && !nama.trim().equals("");

        if (kodeAda || namaAda) { 
            String kodeTampil = (kode == null) ? "" : kode.trim();
            String namaTampil = (nama == null) ? "" : nama.trim();
            String keyword = TCari.getText().trim().toLowerCase();
            String content = (kodeTampil + " " + namaTampil).toLowerCase();

            if (keyword.equals("") || content.contains(keyword)) {
                tabMode.addRow(new Object[]{
                    Boolean.FALSE,  
                    kodeTampil,     
                    namaTampil,     
                    statusLabel,    
                    ""              
                });
            }
        }
    }

    public void emptTeks() {   
        TCari.requestFocus();
    }
    
    public void setNoRawat(String norawat){
        this.norawat=norawat;
    }

    public JTable getTable(){
        return tbKamar;
    }
    
}
